require('dotenv').config({ path: require('path').resolve(__dirname, '../../../.env') });
if (process.env.ALLOW_DEMO_SEED !== 'true' || process.env.NODE_ENV === 'production') {
  throw new Error('Demo seed is quarantined; set ALLOW_DEMO_SEED=true outside production to run explicitly');
}
if (!process.env.DEMO_SEED_PASSWORD || process.env.DEMO_SEED_PASSWORD.length < 12) {
  throw new Error('DEMO_SEED_PASSWORD must be explicitly supplied with at least 12 characters');
}
const bcrypt = require('bcryptjs');
const { sequelize, User, Employee, LearningTrack, SkillGap, Certification, Course, ROIMeasurement,
  MentorshipProgram, TrainingEvent, PerformanceReview, LearningBudget, CompetencyFramework,
  OnboardingPlan, TeamGoal, KnowledgeBase, FeedbackSurvey, SuccessionPlan, ComplianceTraining,
  CareerPath, LearningResource, AssessmentResult, WellnessProgram } = require('../models');

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Connected to database.');
    await sequelize.sync({ force: true });
    console.log('Tables created.');

    const hashedPassword = await bcrypt.hash(process.env.DEMO_SEED_PASSWORD, 10);
    await User.bulkCreate([
      { email: 'admin@company.com', password: hashedPassword, name: 'Admin User', role: 'admin' },
      { email: 'manager@company.com', password: hashedPassword, name: 'Sarah Manager', role: 'manager' },
      { email: 'employee@company.com', password: hashedPassword, name: 'John Employee', role: 'employee' },
    ]);
    console.log('Users seeded.');

    await Employee.bulkCreate([
      { name: 'Alice Johnson', email: 'alice@company.com', department: 'Engineering', position: 'Software Engineer', level: 'Senior', hireDate: '2020-03-15', skills: ['JavaScript', 'React', 'Node.js', 'Python'], learningBudget: 2000, budgetUsed: 450 },
      { name: 'Bob Smith', email: 'bob@company.com', department: 'Engineering', position: 'DevOps Engineer', level: 'Mid', hireDate: '2021-07-01', skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'], learningBudget: 1500, budgetUsed: 300 },
      { name: 'Carol Williams', email: 'carol@company.com', department: 'Data Science', position: 'Data Analyst', level: 'Junior', hireDate: '2023-01-10', skills: ['Python', 'SQL', 'Tableau'], learningBudget: 1200, budgetUsed: 0 },
      { name: 'David Brown', email: 'david@company.com', department: 'Product', position: 'Product Manager', level: 'Senior', hireDate: '2019-06-20', skills: ['Agile', 'Jira', 'User Research', 'Analytics'], learningBudget: 1800, budgetUsed: 600 },
      { name: 'Eva Martinez', email: 'eva@company.com', department: 'Design', position: 'UX Designer', level: 'Mid', hireDate: '2022-02-14', skills: ['Figma', 'Sketch', 'User Testing', 'Prototyping'], learningBudget: 1500, budgetUsed: 200 },
      { name: 'Frank Lee', email: 'frank@company.com', department: 'Engineering', position: 'Backend Engineer', level: 'Senior', hireDate: '2018-11-05', skills: ['Java', 'Spring Boot', 'PostgreSQL', 'Redis'], learningBudget: 2000, budgetUsed: 800 },
      { name: 'Grace Chen', email: 'grace@company.com', department: 'Marketing', position: 'Marketing Analyst', level: 'Mid', hireDate: '2021-09-01', skills: ['Google Analytics', 'SEO', 'Content Strategy'], learningBudget: 1200, budgetUsed: 150 },
      { name: 'Henry Wilson', email: 'henry@company.com', department: 'Engineering', position: 'Frontend Engineer', level: 'Junior', hireDate: '2023-06-15', skills: ['HTML', 'CSS', 'JavaScript', 'React'], learningBudget: 1500, budgetUsed: 0 },
      { name: 'Iris Taylor', email: 'iris@company.com', department: 'HR', position: 'HR Specialist', level: 'Mid', hireDate: '2020-08-20', skills: ['Recruiting', 'HRIS', 'Compliance'], learningBudget: 1000, budgetUsed: 350 },
      { name: 'Jack Anderson', email: 'jack@company.com', department: 'Finance', position: 'Financial Analyst', level: 'Senior', hireDate: '2019-04-10', skills: ['Excel', 'Financial Modeling', 'SAP', 'Power BI'], learningBudget: 1800, budgetUsed: 500 },
      { name: 'Karen Davis', email: 'karen@company.com', department: 'Engineering', position: 'QA Engineer', level: 'Mid', hireDate: '2021-03-22', skills: ['Selenium', 'Jest', 'Cypress', 'API Testing'], learningBudget: 1500, budgetUsed: 250 },
      { name: 'Leo Garcia', email: 'leo@company.com', department: 'Data Science', position: 'ML Engineer', level: 'Senior', hireDate: '2020-01-08', skills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps'], learningBudget: 2500, budgetUsed: 1200 },
      { name: 'Maria Rodriguez', email: 'maria@company.com', department: 'Sales', position: 'Sales Manager', level: 'Senior', hireDate: '2018-09-15', skills: ['Salesforce', 'Negotiation', 'CRM', 'Leadership'], learningBudget: 1800, budgetUsed: 400 },
      { name: 'Nathan Park', email: 'nathan@company.com', department: 'Security', position: 'Security Engineer', level: 'Mid', hireDate: '2022-05-01', skills: ['Network Security', 'Penetration Testing', 'SIEM'], learningBudget: 2000, budgetUsed: 600 },
      { name: 'Olivia White', email: 'olivia@company.com', department: 'Engineering', position: 'Mobile Developer', level: 'Mid', hireDate: '2021-11-10', skills: ['React Native', 'Swift', 'Kotlin', 'Flutter'], learningBudget: 1500, budgetUsed: 300 },
      { name: 'Peter Kim', email: 'peter@company.com', department: 'Engineering', position: 'Cloud Architect', level: 'Lead', hireDate: '2017-06-01', skills: ['AWS', 'Azure', 'GCP', 'Microservices', 'System Design'], learningBudget: 3000, budgetUsed: 1500 },
    ]);
    console.log('Employees seeded.');

    await LearningTrack.bulkCreate([
      { employeeId: 1, title: 'Advanced React Patterns', description: 'Master advanced React patterns including compound components, render props, and hooks', category: 'Frontend', priority: 'High', status: 'In Progress', targetDate: '2026-06-30', progress: 45, estimatedHours: 40, completedHours: 18 },
      { employeeId: 1, title: 'System Design Fundamentals', description: 'Learn distributed systems design for senior engineering roles', category: 'Architecture', priority: 'High', status: 'Not Started', targetDate: '2026-09-30', progress: 0, estimatedHours: 60, completedHours: 0 },
      { employeeId: 2, title: 'Kubernetes Advanced Administration', description: 'Deep dive into K8s cluster management', category: 'DevOps', priority: 'High', status: 'In Progress', targetDate: '2026-05-15', progress: 60, estimatedHours: 50, completedHours: 30 },
      { employeeId: 3, title: 'Machine Learning Foundations', description: 'Build ML foundations for data science role', category: 'Data Science', priority: 'High', status: 'In Progress', targetDate: '2026-08-30', progress: 25, estimatedHours: 80, completedHours: 20 },
      { employeeId: 4, title: 'Technical Product Management', description: 'Deepen technical understanding', category: 'Product', priority: 'Medium', status: 'In Progress', targetDate: '2026-07-15', progress: 55, estimatedHours: 30, completedHours: 16 },
      { employeeId: 5, title: 'Design Systems Architecture', description: 'Create scalable design systems', category: 'Design', priority: 'Medium', status: 'Not Started', targetDate: '2026-10-01', progress: 0, estimatedHours: 35, completedHours: 0 },
      { employeeId: 6, title: 'Microservices with Spring Cloud', description: 'Advanced microservices patterns', category: 'Backend', priority: 'High', status: 'Completed', targetDate: '2026-03-01', progress: 100, estimatedHours: 45, completedHours: 45 },
      { employeeId: 7, title: 'Data-Driven Marketing', description: 'Advanced analytics for marketing', category: 'Marketing', priority: 'Medium', status: 'In Progress', targetDate: '2026-06-30', progress: 35, estimatedHours: 25, completedHours: 9 },
      { employeeId: 8, title: 'TypeScript Mastery', description: 'Advanced TypeScript', category: 'Frontend', priority: 'High', status: 'In Progress', targetDate: '2026-05-30', progress: 40, estimatedHours: 30, completedHours: 12 },
      { employeeId: 9, title: 'People Analytics', description: 'Data-driven HR decision making', category: 'HR', priority: 'Medium', status: 'Not Started', targetDate: '2026-08-15', progress: 0, estimatedHours: 20, completedHours: 0 },
      { employeeId: 10, title: 'Advanced Financial Modeling', description: 'Complex financial models', category: 'Finance', priority: 'High', status: 'In Progress', targetDate: '2026-04-30', progress: 70, estimatedHours: 35, completedHours: 24 },
      { employeeId: 11, title: 'Test Automation Framework Design', description: 'Build scalable test frameworks', category: 'QA', priority: 'High', status: 'In Progress', targetDate: '2026-06-15', progress: 50, estimatedHours: 40, completedHours: 20 },
      { employeeId: 12, title: 'Deep Learning Specialization', description: 'Advanced neural networks', category: 'AI/ML', priority: 'High', status: 'In Progress', targetDate: '2026-07-30', progress: 65, estimatedHours: 100, completedHours: 65 },
      { employeeId: 13, title: 'Strategic Sales Leadership', description: 'Executive-level sales strategy', category: 'Sales', priority: 'Medium', status: 'In Progress', targetDate: '2026-05-30', progress: 40, estimatedHours: 25, completedHours: 10 },
      { employeeId: 14, title: 'Cloud Security Certification Prep', description: 'CCSP prep', category: 'Security', priority: 'High', status: 'In Progress', targetDate: '2026-06-30', progress: 30, estimatedHours: 60, completedHours: 18 },
      { employeeId: 15, title: 'Cross-Platform Development with Flutter', description: 'Advanced Flutter', category: 'Mobile', priority: 'Medium', status: 'Not Started', targetDate: '2026-09-01', progress: 0, estimatedHours: 45, completedHours: 0 },
    ]);
    console.log('Learning Tracks seeded.');

    await SkillGap.bulkCreate([
      { employeeId: 1, skillName: 'System Design', currentLevel: 2, requiredLevel: 4, gapScore: 4.0, category: 'Architecture', priority: 'Critical', recommendedAction: 'Enroll in system design course', status: 'Identified' },
      { employeeId: 1, skillName: 'GraphQL', currentLevel: 1, requiredLevel: 3, gapScore: 3.0, category: 'API', priority: 'High', recommendedAction: 'Complete GraphQL fundamentals', status: 'In Progress' },
      { employeeId: 2, skillName: 'Istio Service Mesh', currentLevel: 1, requiredLevel: 4, gapScore: 4.5, category: 'DevOps', priority: 'High', recommendedAction: 'Hands-on labs with Istio', status: 'Identified' },
      { employeeId: 3, skillName: 'Deep Learning', currentLevel: 1, requiredLevel: 4, gapScore: 4.5, category: 'AI/ML', priority: 'Critical', recommendedAction: 'Complete deep learning specialization', status: 'In Progress' },
      { employeeId: 3, skillName: 'Statistics', currentLevel: 2, requiredLevel: 4, gapScore: 3.5, category: 'Mathematics', priority: 'High', recommendedAction: 'Take advanced statistics course', status: 'Identified' },
      { employeeId: 4, skillName: 'SQL & Data Analysis', currentLevel: 2, requiredLevel: 3, gapScore: 2.0, category: 'Technical', priority: 'Medium', recommendedAction: 'Practice SQL queries', status: 'In Progress' },
      { employeeId: 5, skillName: 'Design Systems', currentLevel: 2, requiredLevel: 4, gapScore: 3.5, category: 'Design', priority: 'High', recommendedAction: 'Study major design systems', status: 'Identified' },
      { employeeId: 6, skillName: 'Cloud Architecture', currentLevel: 2, requiredLevel: 4, gapScore: 3.5, category: 'Cloud', priority: 'High', recommendedAction: 'AWS SA cert prep', status: 'In Progress' },
      { employeeId: 7, skillName: 'Marketing Automation', currentLevel: 1, requiredLevel: 3, gapScore: 3.0, category: 'Marketing', priority: 'Medium', recommendedAction: 'HubSpot certification', status: 'Identified' },
      { employeeId: 8, skillName: 'Testing & TDD', currentLevel: 1, requiredLevel: 3, gapScore: 3.0, category: 'Engineering', priority: 'High', recommendedAction: 'Learn Jest and RTL', status: 'Identified' },
      { employeeId: 9, skillName: 'Data Visualization', currentLevel: 1, requiredLevel: 3, gapScore: 3.0, category: 'Analytics', priority: 'Medium', recommendedAction: 'Learn Tableau or Power BI', status: 'Identified' },
      { employeeId: 10, skillName: 'Python for Finance', currentLevel: 1, requiredLevel: 3, gapScore: 3.0, category: 'Programming', priority: 'Medium', recommendedAction: 'Python for finance course', status: 'In Progress' },
      { employeeId: 12, skillName: 'MLOps', currentLevel: 2, requiredLevel: 5, gapScore: 4.5, category: 'Operations', priority: 'Critical', recommendedAction: 'Learn MLflow, Kubeflow', status: 'In Progress' },
      { employeeId: 14, skillName: 'Cloud Security', currentLevel: 2, requiredLevel: 5, gapScore: 4.5, category: 'Security', priority: 'Critical', recommendedAction: 'Pursue CCSP certification', status: 'In Progress' },
      { employeeId: 15, skillName: 'iOS Development', currentLevel: 2, requiredLevel: 4, gapScore: 3.5, category: 'Mobile', priority: 'High', recommendedAction: 'Advanced Swift course', status: 'Identified' },
      { employeeId: 16, skillName: 'AI/ML Integration', currentLevel: 1, requiredLevel: 4, gapScore: 4.0, category: 'AI', priority: 'High', recommendedAction: 'Learn ML model deployment', status: 'Identified' },
    ]);
    console.log('Skill Gaps seeded.');

    await Certification.bulkCreate([
      { employeeId: 1, name: 'AWS Certified Developer - Associate', provider: 'Amazon Web Services', category: 'Cloud', dateObtained: '2024-06-15', expiryDate: '2027-06-15', status: 'Active', cost: 300, credentialId: 'AWS-DEV-001' },
      { employeeId: 2, name: 'Certified Kubernetes Administrator', provider: 'CNCF', category: 'DevOps', dateObtained: '2024-03-20', expiryDate: '2027-03-20', status: 'Active', cost: 395, credentialId: 'CKA-002' },
      { employeeId: 2, name: 'HashiCorp Terraform Associate', provider: 'HashiCorp', category: 'Infrastructure', dateObtained: '2023-11-10', expiryDate: '2025-11-10', status: 'Active', cost: 70, credentialId: 'HCT-003' },
      { employeeId: 3, name: 'Google Data Analytics Certificate', provider: 'Google', category: 'Data', dateObtained: '2024-01-05', status: 'Active', cost: 49, credentialId: 'GDA-004' },
      { employeeId: 4, name: 'Certified Scrum Product Owner', provider: 'Scrum Alliance', category: 'Agile', dateObtained: '2023-08-15', expiryDate: '2025-08-15', status: 'Active', cost: 500, credentialId: 'CSPO-005' },
      { employeeId: 5, name: 'Google UX Design Certificate', provider: 'Google', category: 'Design', dateObtained: '2024-02-28', status: 'Active', cost: 49, credentialId: 'GUXD-006' },
      { employeeId: 6, name: 'Oracle Certified Professional Java SE', provider: 'Oracle', category: 'Programming', dateObtained: '2022-05-10', status: 'Active', cost: 245, credentialId: 'OCP-007' },
      { employeeId: 6, name: 'AWS Solutions Architect - Associate', provider: 'AWS', category: 'Cloud', status: 'In Progress', cost: 300 },
      { employeeId: 10, name: 'CFA Level II', provider: 'CFA Institute', category: 'Finance', dateObtained: '2023-06-01', status: 'Active', cost: 1200, credentialId: 'CFA-008' },
      { employeeId: 11, name: 'ISTQB Advanced Test Analyst', provider: 'ISTQB', category: 'QA', dateObtained: '2024-04-10', status: 'Active', cost: 250, credentialId: 'ISTQB-009' },
      { employeeId: 12, name: 'TensorFlow Developer Certificate', provider: 'Google', category: 'AI/ML', dateObtained: '2024-01-20', status: 'Active', cost: 100, credentialId: 'TFD-010' },
      { employeeId: 12, name: 'AWS Machine Learning Specialty', provider: 'AWS', category: 'AI/ML', status: 'In Progress', cost: 300 },
      { employeeId: 13, name: 'Salesforce Certified Administrator', provider: 'Salesforce', category: 'CRM', dateObtained: '2023-03-15', expiryDate: '2026-03-15', status: 'Active', cost: 200, credentialId: 'SFCA-011' },
      { employeeId: 14, name: 'CompTIA Security+', provider: 'CompTIA', category: 'Security', dateObtained: '2023-09-01', expiryDate: '2026-09-01', status: 'Active', cost: 392, credentialId: 'SEC-012' },
      { employeeId: 14, name: 'CCSP', provider: 'ISC2', category: 'Security', status: 'Planned', cost: 599 },
      { employeeId: 16, name: 'AWS Solutions Architect - Professional', provider: 'AWS', category: 'Cloud', dateObtained: '2023-12-01', expiryDate: '2026-12-01', status: 'Active', cost: 300, credentialId: 'AWSAP-013' },
    ]);
    console.log('Certifications seeded.');

    await Course.bulkCreate([
      { title: 'Complete React Developer', provider: 'Udemy', category: 'Frontend', level: 'Intermediate', duration: '40 hours', cost: 89.99, rating: 4.7, description: 'Master React with hooks, Redux, GraphQL', skills: ['React', 'Redux', 'GraphQL'], format: 'Self-Paced' },
      { title: 'AWS Solutions Architect Associate', provider: 'A Cloud Guru', category: 'Cloud', level: 'Intermediate', duration: '50 hours', cost: 299.00, rating: 4.8, description: 'Comprehensive AWS SAA exam prep', skills: ['AWS', 'EC2', 'S3', 'Lambda'], format: 'Online' },
      { title: 'Machine Learning Specialization', provider: 'Coursera', category: 'AI/ML', level: 'Intermediate', duration: '80 hours', cost: 49.00, rating: 4.9, description: 'Andrew Ng ML course', skills: ['Machine Learning', 'Python', 'TensorFlow'], format: 'Self-Paced' },
      { title: 'Kubernetes for Developers', provider: 'Linux Foundation', category: 'DevOps', level: 'Intermediate', duration: '35 hours', cost: 395.00, rating: 4.6, description: 'Containerized apps on K8s', skills: ['Kubernetes', 'Docker', 'Helm'], format: 'Online' },
      { title: 'Advanced Python Programming', provider: 'Pluralsight', category: 'Programming', level: 'Advanced', duration: '25 hours', cost: 45.00, rating: 4.5, description: 'Advanced Python concepts', skills: ['Python', 'Async', 'Testing'], format: 'Self-Paced' },
      { title: 'UX Design Professional Certificate', provider: 'Google', category: 'Design', level: 'Beginner', duration: '200 hours', cost: 49.00, rating: 4.8, description: 'Complete UX design program', skills: ['UX Research', 'Prototyping'], format: 'Self-Paced' },
      { title: 'Financial Modeling & Valuation', provider: 'Wall Street Prep', category: 'Finance', level: 'Advanced', duration: '45 hours', cost: 499.00, rating: 4.7, description: 'Professional financial models', skills: ['Financial Modeling', 'Excel'], format: 'Online' },
      { title: 'Product Management Fundamentals', provider: 'Product School', category: 'Product', level: 'Intermediate', duration: '30 hours', cost: 199.00, rating: 4.6, description: 'Learn PM from Silicon Valley PMs', skills: ['Product Strategy', 'Roadmapping'], format: 'Hybrid' },
      { title: 'Cybersecurity Bootcamp', provider: 'SANS', category: 'Security', level: 'Advanced', duration: '60 hours', cost: 799.00, rating: 4.9, description: 'Intensive cybersecurity training', skills: ['Penetration Testing', 'Incident Response'], format: 'In-Person' },
      { title: 'Data Visualization with Tableau', provider: 'Coursera', category: 'Analytics', level: 'Beginner', duration: '20 hours', cost: 49.00, rating: 4.5, description: 'Compelling data visualizations', skills: ['Tableau', 'Data Viz'], format: 'Self-Paced' },
      { title: 'Spring Boot Microservices', provider: 'Udemy', category: 'Backend', level: 'Advanced', duration: '35 hours', cost: 94.99, rating: 4.6, description: 'Production microservices', skills: ['Spring Boot', 'Microservices', 'Kafka'], format: 'Self-Paced' },
      { title: 'React Native Practical Guide', provider: 'Udemy', category: 'Mobile', level: 'Intermediate', duration: '30 hours', cost: 84.99, rating: 4.7, description: 'Build native mobile apps', skills: ['React Native', 'iOS', 'Android'], format: 'Self-Paced' },
      { title: 'MLOps Engineering', provider: 'Coursera', category: 'AI/ML', level: 'Advanced', duration: '40 hours', cost: 79.00, rating: 4.6, description: 'Production ML pipelines', skills: ['MLOps', 'MLflow'], format: 'Online' },
      { title: 'Leadership & Management', provider: 'LinkedIn Learning', category: 'Leadership', level: 'Intermediate', duration: '15 hours', cost: 29.99, rating: 4.4, description: 'Essential leadership skills', skills: ['Leadership', 'Communication'], format: 'Self-Paced' },
      { title: 'System Design Interview Prep', provider: 'Educative', category: 'Architecture', level: 'Advanced', duration: '25 hours', cost: 79.00, rating: 4.8, description: 'Master system design', skills: ['System Design', 'Distributed Systems'], format: 'Self-Paced' },
      { title: 'HubSpot Marketing Certification', provider: 'HubSpot Academy', category: 'Marketing', level: 'Beginner', duration: '12 hours', cost: 0.00, rating: 4.5, description: 'Free inbound marketing cert', skills: ['Inbound Marketing', 'SEO'], format: 'Online' },
    ]);
    console.log('Courses seeded.');

    await ROIMeasurement.bulkCreate([
      { employeeId: 1, programName: 'React Advanced Training', investmentAmount: 450, returnAmount: 1200, roiPercentage: 166.67, measurementDate: '2025-12-01', category: 'Technical', metrics: { productivity: '+25%', codeQuality: '+30%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 2, programName: 'Kubernetes Certification Prep', investmentAmount: 300, returnAmount: 800, roiPercentage: 166.67, measurementDate: '2025-11-15', category: 'DevOps', metrics: { deployFrequency: '+40%', incidentRate: '-20%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 3, programName: 'Data Analytics Bootcamp', investmentAmount: 0, returnAmount: 0, roiPercentage: 0, measurementDate: '2026-03-01', category: 'Data', metrics: { reportsGenerated: '+50%' }, period: 'Q1 2026', status: 'Measuring' },
      { employeeId: 4, programName: 'Product Strategy Workshop', investmentAmount: 600, returnAmount: 1500, roiPercentage: 150.00, measurementDate: '2025-10-01', category: 'Product', metrics: { featureAdoption: '+35%' }, period: 'Q3 2025', status: 'Positive' },
      { employeeId: 5, programName: 'Figma Advanced Workshop', investmentAmount: 200, returnAmount: 500, roiPercentage: 150.00, measurementDate: '2025-12-15', category: 'Design', metrics: { designIterations: '-30%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 6, programName: 'Spring Cloud Training', investmentAmount: 800, returnAmount: 2400, roiPercentage: 200.00, measurementDate: '2025-09-01', category: 'Technical', metrics: { systemReliability: '+35%' }, period: 'Q3 2025', status: 'Positive' },
      { employeeId: 7, programName: 'SEO Certification', investmentAmount: 150, returnAmount: 300, roiPercentage: 100.00, measurementDate: '2025-12-01', category: 'Marketing', metrics: { organicTraffic: '+20%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 8, programName: 'JavaScript Fundamentals', investmentAmount: 0, returnAmount: 0, roiPercentage: 0, measurementDate: '2026-02-01', category: 'Technical', metrics: { tasksCompleted: '+30%' }, period: 'Q1 2026', status: 'Measuring' },
      { employeeId: 9, programName: 'HR Analytics Course', investmentAmount: 350, returnAmount: 700, roiPercentage: 100.00, measurementDate: '2025-11-01', category: 'HR', metrics: { hiringEfficiency: '+20%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 10, programName: 'CFA Level II Prep', investmentAmount: 500, returnAmount: 2000, roiPercentage: 300.00, measurementDate: '2025-08-01', category: 'Finance', metrics: { forecastAccuracy: '+30%' }, period: 'Q3 2025', status: 'Positive' },
      { employeeId: 11, programName: 'Automation Framework Training', investmentAmount: 250, returnAmount: 600, roiPercentage: 140.00, measurementDate: '2025-12-15', category: 'QA', metrics: { testCoverage: '+35%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 12, programName: 'Deep Learning Specialization', investmentAmount: 1200, returnAmount: 3600, roiPercentage: 200.00, measurementDate: '2025-10-01', category: 'AI/ML', metrics: { modelAccuracy: '+15%' }, period: 'Q3 2025', status: 'Positive' },
      { employeeId: 13, programName: 'Sales Leadership Program', investmentAmount: 400, returnAmount: 1000, roiPercentage: 150.00, measurementDate: '2025-11-15', category: 'Sales', metrics: { teamRevenue: '+18%' }, period: 'Q4 2025', status: 'Positive' },
      { employeeId: 14, programName: 'Security+ Certification', investmentAmount: 600, returnAmount: 1500, roiPercentage: 150.00, measurementDate: '2025-09-15', category: 'Security', metrics: { vulnerabilitiesFound: '+40%' }, period: 'Q3 2025', status: 'Positive' },
      { employeeId: 15, programName: 'Mobile App Performance', investmentAmount: 300, returnAmount: 150, roiPercentage: -50.00, measurementDate: '2025-12-01', category: 'Mobile', metrics: { appLoadTime: '-10%' }, period: 'Q4 2025', status: 'Negative' },
      { employeeId: 16, programName: 'Cloud Architecture Masterclass', investmentAmount: 1500, returnAmount: 5000, roiPercentage: 233.33, measurementDate: '2025-08-01', category: 'Cloud', metrics: { costOptimization: '-25%' }, period: 'Q3 2025', status: 'Positive' },
    ]);
    console.log('ROI Measurements seeded.');

    // ========== NEW FEATURES SEED DATA ==========

    await MentorshipProgram.bulkCreate([
      { mentorId: 6, menteeId: 1, programName: 'Senior Engineer Mentorship', focus: 'System Design & Architecture', status: 'Active', startDate: '2026-01-15', meetingFrequency: 'Weekly', goalDescription: 'Prepare Alice for Staff Engineer role', rating: 4.5 },
      { mentorId: 16, menteeId: 2, programName: 'Cloud Infrastructure Growth', focus: 'Cloud Architecture', status: 'Active', startDate: '2026-01-01', meetingFrequency: 'Bi-weekly', goalDescription: 'Help Bob transition to cloud architect role', rating: 4.0 },
      { mentorId: 12, menteeId: 3, programName: 'Data Science Acceleration', focus: 'Machine Learning', status: 'Active', startDate: '2025-11-01', meetingFrequency: 'Weekly', goalDescription: 'Guide Carol from analyst to data scientist', rating: 4.8 },
      { mentorId: 4, menteeId: 7, programName: 'Marketing Analytics Mentorship', focus: 'Data-Driven Marketing', status: 'Active', startDate: '2026-02-01', meetingFrequency: 'Bi-weekly', goalDescription: 'Help Grace leverage analytics in campaigns', rating: 3.5 },
      { mentorId: 1, menteeId: 8, programName: 'Frontend Engineering Foundations', focus: 'React & TypeScript', status: 'Active', startDate: '2025-12-01', meetingFrequency: 'Weekly', goalDescription: 'Bring Henry up to mid-level frontend', rating: 4.2 },
      { mentorId: 13, menteeId: 9, programName: 'HR Leadership Path', focus: 'People Management', status: 'Active', startDate: '2026-01-10', meetingFrequency: 'Monthly', goalDescription: 'Develop Iris for HR Manager role', rating: 4.0 },
      { mentorId: 6, menteeId: 11, programName: 'QA to SDET Transition', focus: 'Software Dev in Test', status: 'Completed', startDate: '2025-06-01', endDate: '2025-12-15', meetingFrequency: 'Weekly', goalDescription: 'Help Karen develop engineering skills', rating: 4.7 },
      { mentorId: 16, menteeId: 14, programName: 'Security Architecture Mentorship', focus: 'Cloud Security', status: 'Active', startDate: '2026-02-15', meetingFrequency: 'Bi-weekly', goalDescription: 'Prepare Nathan for security architect role', rating: 4.3 },
      { mentorId: 1, menteeId: 15, programName: 'Cross-Platform Mobile Mentoring', focus: 'Mobile Architecture', status: 'Paused', startDate: '2025-09-01', meetingFrequency: 'Bi-weekly', goalDescription: 'Guide Olivia on mobile architecture patterns', progressNotes: 'Paused due to project deadline', rating: 3.8 },
      { mentorId: 10, menteeId: 3, programName: 'Financial Data Analysis', focus: 'Financial Analytics', status: 'Active', startDate: '2026-03-01', meetingFrequency: 'Monthly', goalDescription: 'Teach Carol financial analysis techniques', rating: 0 },
      { mentorId: 4, menteeId: 5, programName: 'Product Design Alignment', focus: 'Product Thinking', status: 'Active', startDate: '2026-01-20', meetingFrequency: 'Bi-weekly', goalDescription: 'Help Eva think more product-oriented', rating: 4.1 },
      { mentorId: 12, menteeId: 16, programName: 'AI Integration for Cloud', focus: 'AI/ML in Cloud', status: 'Active', startDate: '2026-02-01', meetingFrequency: 'Monthly', goalDescription: 'Help Peter integrate AI into cloud architecture', rating: 4.4 },
      { mentorId: 13, menteeId: 7, programName: 'Sales & Marketing Synergy', focus: 'Revenue Growth', status: 'Completed', startDate: '2025-04-01', endDate: '2025-10-30', meetingFrequency: 'Monthly', goalDescription: 'Align marketing with sales goals', rating: 4.6 },
      { mentorId: 6, menteeId: 2, programName: 'Java Backend Mastery', focus: 'Backend Architecture', status: 'Completed', startDate: '2025-01-15', endDate: '2025-07-15', meetingFrequency: 'Weekly', goalDescription: 'Strengthen Java backend skills', rating: 4.9 },
      { mentorId: 16, menteeId: 6, programName: 'Cloud Architect Path', focus: 'Architecture Leadership', status: 'Active', startDate: '2026-03-01', meetingFrequency: 'Monthly', goalDescription: 'Prepare Frank for cloud architect role', rating: 0 },
    ]);
    console.log('Mentorship Programs seeded.');

    await TrainingEvent.bulkCreate([
      { title: 'React 19 Deep Dive Workshop', type: 'Workshop', facilitator: 'Alice Johnson', location: 'Conference Room A', startDate: '2026-04-15', endDate: '2026-04-16', capacity: 30, enrolled: 22, cost: 0, status: 'Upcoming', description: 'Hands-on workshop covering React 19 features', category: 'Technical' },
      { title: 'AWS re:Invent Prep Seminar', type: 'Seminar', facilitator: 'Peter Kim', location: 'Virtual', startDate: '2026-05-01', endDate: '2026-05-01', capacity: 100, enrolled: 67, cost: 0, status: 'Upcoming', description: 'Preview of AWS latest services', category: 'Cloud' },
      { title: 'Leadership Excellence Bootcamp', type: 'Bootcamp', facilitator: 'External - John Maxwell', location: 'Training Center', startDate: '2026-03-20', endDate: '2026-03-22', capacity: 20, enrolled: 18, cost: 500, status: 'Upcoming', description: 'Intensive leadership development program', category: 'Leadership' },
      { title: 'Data Science Summit 2026', type: 'Conference', facilitator: 'Multiple Speakers', location: 'Grand Hotel', startDate: '2026-06-10', endDate: '2026-06-12', capacity: 200, enrolled: 145, cost: 350, status: 'Upcoming', description: 'Annual data science conference', category: 'Data Science' },
      { title: 'Agile at Scale Webinar', type: 'Webinar', facilitator: 'David Brown', location: 'Virtual', startDate: '2026-04-05', endDate: '2026-04-05', capacity: 500, enrolled: 189, cost: 0, status: 'Upcoming', description: 'Scaling agile practices across the organization', category: 'Agile' },
      { title: 'Cybersecurity Awareness Training', type: 'Workshop', facilitator: 'Nathan Park', location: 'All Offices', startDate: '2026-03-10', endDate: '2026-03-10', capacity: 300, enrolled: 245, cost: 0, status: 'In Progress', description: 'Mandatory security awareness session', category: 'Security' },
      { title: 'Design Thinking Workshop', type: 'Workshop', facilitator: 'Eva Martinez', location: 'Design Lab', startDate: '2026-04-20', endDate: '2026-04-21', capacity: 25, enrolled: 25, cost: 0, status: 'Upcoming', description: 'Learn design thinking methodology', category: 'Design' },
      { title: 'Python for Data Analysis Bootcamp', type: 'Bootcamp', facilitator: 'Leo Garcia', location: 'Training Room B', startDate: '2025-11-15', endDate: '2025-11-19', capacity: 20, enrolled: 20, cost: 200, status: 'Completed', description: 'Intensive Python data analysis training', category: 'Data Science' },
      { title: 'Microservices Architecture Seminar', type: 'Seminar', facilitator: 'Frank Lee', location: 'Virtual', startDate: '2026-05-15', endDate: '2026-05-15', capacity: 80, enrolled: 34, cost: 0, status: 'Upcoming', description: 'Best practices for microservices', category: 'Architecture' },
      { title: 'Sales Mastery Conference', type: 'Conference', facilitator: 'External - Grant Cardone', location: 'Convention Center', startDate: '2026-07-01', endDate: '2026-07-02', capacity: 150, enrolled: 89, cost: 450, status: 'Upcoming', description: 'Annual sales excellence conference', category: 'Sales' },
      { title: 'Mental Health First Aid', type: 'Workshop', facilitator: 'External - Dr. Sarah Lin', location: 'Wellness Center', startDate: '2026-04-08', endDate: '2026-04-08', capacity: 40, enrolled: 35, cost: 0, status: 'Upcoming', description: 'Mental health awareness for managers', category: 'Wellness' },
      { title: 'DevOps CI/CD Pipeline Workshop', type: 'Workshop', facilitator: 'Bob Smith', location: 'Lab C', startDate: '2026-03-25', endDate: '2026-03-26', capacity: 20, enrolled: 16, cost: 0, status: 'Upcoming', description: 'Build production CI/CD pipelines', category: 'DevOps' },
      { title: 'Financial Planning Seminar', type: 'Seminar', facilitator: 'Jack Anderson', location: 'Virtual', startDate: '2026-04-12', endDate: '2026-04-12', capacity: 50, enrolled: 28, cost: 0, status: 'Upcoming', description: 'Personal and corporate financial planning', category: 'Finance' },
      { title: 'AI Ethics & Governance Workshop', type: 'Workshop', facilitator: 'External - Dr. Kate Crawford', location: 'Virtual', startDate: '2026-05-20', endDate: '2026-05-20', capacity: 200, enrolled: 112, cost: 0, status: 'Upcoming', description: 'Responsible AI development practices', category: 'AI/Ethics' },
      { title: 'Q1 Engineering All-Hands', type: 'Seminar', facilitator: 'CTO', location: 'Main Auditorium', startDate: '2026-01-15', endDate: '2026-01-15', capacity: 200, enrolled: 178, cost: 0, status: 'Completed', description: 'Quarterly engineering review and planning', category: 'General' },
    ]);
    console.log('Training Events seeded.');

    await PerformanceReview.bulkCreate([
      { employeeId: 1, reviewerName: 'Sarah Manager', reviewPeriod: '2025 Annual', overallRating: 4.2, technicalScore: 4.5, communicationScore: 4.0, leadershipScore: 3.8, learningScore: 4.5, strengths: 'Excellent technical skills, strong React expertise', areasForImprovement: 'System design, cross-team collaboration', status: 'Completed', reviewDate: '2026-01-15' },
      { employeeId: 2, reviewerName: 'Sarah Manager', reviewPeriod: '2025 Annual', overallRating: 3.8, technicalScore: 4.0, communicationScore: 3.5, leadershipScore: 3.5, learningScore: 4.0, strengths: 'Strong DevOps skills, good automation', areasForImprovement: 'Documentation, communication with non-tech teams', status: 'Completed', reviewDate: '2026-01-15' },
      { employeeId: 3, reviewerName: 'Leo Garcia', reviewPeriod: '2025 Annual', overallRating: 3.5, technicalScore: 3.0, communicationScore: 4.0, leadershipScore: 3.0, learningScore: 4.5, strengths: 'Great learner, strong analytical mindset', areasForImprovement: 'ML skills, statistical depth', status: 'Completed', reviewDate: '2026-01-20' },
      { employeeId: 4, reviewerName: 'VP Product', reviewPeriod: '2025 Annual', overallRating: 4.5, technicalScore: 3.5, communicationScore: 4.8, leadershipScore: 4.5, learningScore: 4.2, strengths: 'Excellent stakeholder management', areasForImprovement: 'Technical depth, data analysis', status: 'Completed', reviewDate: '2026-01-10' },
      { employeeId: 5, reviewerName: 'Design Director', reviewPeriod: '2025 Annual', overallRating: 4.0, technicalScore: 4.0, communicationScore: 4.2, leadershipScore: 3.5, learningScore: 3.8, strengths: 'Creative problem solving, user empathy', areasForImprovement: 'Design systems thinking, design ops', status: 'Completed', reviewDate: '2026-01-18' },
      { employeeId: 6, reviewerName: 'Sarah Manager', reviewPeriod: '2025 Annual', overallRating: 4.5, technicalScore: 4.8, communicationScore: 4.0, leadershipScore: 4.2, learningScore: 4.5, strengths: 'Deep Java expertise, mentoring ability', areasForImprovement: 'Cloud architecture, modern frameworks', status: 'Completed', reviewDate: '2026-01-15' },
      { employeeId: 7, reviewerName: 'Marketing Director', reviewPeriod: '2025 Annual', overallRating: 3.8, technicalScore: 3.5, communicationScore: 4.0, leadershipScore: 3.2, learningScore: 4.0, strengths: 'Good analytical skills, creative campaigns', areasForImprovement: 'Marketing automation, data storytelling', status: 'Submitted', reviewDate: '2026-02-01' },
      { employeeId: 8, reviewerName: 'Sarah Manager', reviewPeriod: 'Q4 2025', overallRating: 3.2, technicalScore: 3.0, communicationScore: 3.5, leadershipScore: 2.8, learningScore: 4.0, strengths: 'Eager learner, good React basics', areasForImprovement: 'TypeScript, testing, code architecture', status: 'Acknowledged', reviewDate: '2026-01-05' },
      { employeeId: 9, reviewerName: 'HR Director', reviewPeriod: '2025 Annual', overallRating: 4.0, technicalScore: 3.5, communicationScore: 4.5, leadershipScore: 3.8, learningScore: 3.5, strengths: 'Strong recruiter, compliance expertise', areasForImprovement: 'People analytics, HR technology', status: 'Completed', reviewDate: '2026-01-20' },
      { employeeId: 10, reviewerName: 'Finance Director', reviewPeriod: '2025 Annual', overallRating: 4.3, technicalScore: 4.5, communicationScore: 4.0, leadershipScore: 4.0, learningScore: 4.5, strengths: 'Excellent financial modeling, CFA progress', areasForImprovement: 'Python automation, presentation skills', status: 'Completed', reviewDate: '2026-01-12' },
      { employeeId: 11, reviewerName: 'QA Lead', reviewPeriod: '2025 Annual', overallRating: 3.8, technicalScore: 4.0, communicationScore: 3.5, leadershipScore: 3.5, learningScore: 4.0, strengths: 'Thorough testing, good automation skills', areasForImprovement: 'Performance testing, leadership', status: 'Completed', reviewDate: '2026-01-15' },
      { employeeId: 12, reviewerName: 'Data Science Director', reviewPeriod: '2025 Annual', overallRating: 4.7, technicalScore: 4.8, communicationScore: 4.2, leadershipScore: 4.5, learningScore: 5.0, strengths: 'Outstanding ML expertise, research capability', areasForImprovement: 'MLOps, stakeholder communication', status: 'Completed', reviewDate: '2026-01-10' },
      { employeeId: 13, reviewerName: 'VP Sales', reviewPeriod: '2025 Annual', overallRating: 4.2, technicalScore: 3.5, communicationScore: 4.5, leadershipScore: 4.5, learningScore: 4.0, strengths: 'Strong leadership, exceeds quota consistently', areasForImprovement: 'Data-driven selling, CRM optimization', status: 'Completed', reviewDate: '2026-01-18' },
      { employeeId: 14, reviewerName: 'CISO', reviewPeriod: '2025 Annual', overallRating: 3.8, technicalScore: 4.0, communicationScore: 3.5, leadershipScore: 3.5, learningScore: 4.2, strengths: 'Strong security fundamentals, proactive', areasForImprovement: 'Cloud security depth, incident response', status: 'Submitted', reviewDate: '2026-02-05' },
      { employeeId: 15, reviewerName: 'Mobile Lead', reviewPeriod: '2025 Annual', overallRating: 3.5, technicalScore: 3.8, communicationScore: 3.5, leadershipScore: 3.0, learningScore: 3.5, strengths: 'Good cross-platform skills', areasForImprovement: 'Native iOS depth, architecture patterns', status: 'Draft', reviewDate: '2026-02-10' },
    ]);
    console.log('Performance Reviews seeded.');

    await LearningBudget.bulkCreate([
      { department: 'Engineering', fiscalYear: 'FY2026', totalBudget: 50000, allocated: 35000, spent: 12500, remaining: 37500, category: 'All Training', approvedBy: 'CTO', status: 'Active', notes: 'Increased 15% from FY2025' },
      { department: 'Data Science', fiscalYear: 'FY2026', totalBudget: 25000, allocated: 18000, spent: 8200, remaining: 16800, category: 'All Training', approvedBy: 'VP Engineering', status: 'Active' },
      { department: 'Product', fiscalYear: 'FY2026', totalBudget: 15000, allocated: 10000, spent: 4500, remaining: 10500, category: 'All Training', approvedBy: 'VP Product', status: 'Active' },
      { department: 'Design', fiscalYear: 'FY2026', totalBudget: 12000, allocated: 8000, spent: 3200, remaining: 8800, category: 'All Training', approvedBy: 'Design Director', status: 'Active' },
      { department: 'Marketing', fiscalYear: 'FY2026', totalBudget: 10000, allocated: 6000, spent: 2100, remaining: 7900, category: 'All Training', approvedBy: 'CMO', status: 'Active' },
      { department: 'Sales', fiscalYear: 'FY2026', totalBudget: 18000, allocated: 12000, spent: 5400, remaining: 12600, category: 'All Training', approvedBy: 'VP Sales', status: 'Active' },
      { department: 'HR', fiscalYear: 'FY2026', totalBudget: 8000, allocated: 5000, spent: 2800, remaining: 5200, category: 'All Training', approvedBy: 'CHRO', status: 'Active' },
      { department: 'Finance', fiscalYear: 'FY2026', totalBudget: 12000, allocated: 8500, spent: 4000, remaining: 8000, category: 'All Training', approvedBy: 'CFO', status: 'Active' },
      { department: 'Security', fiscalYear: 'FY2026', totalBudget: 20000, allocated: 15000, spent: 7800, remaining: 12200, category: 'All Training', approvedBy: 'CISO', status: 'Active' },
      { department: 'Engineering', fiscalYear: 'FY2026', totalBudget: 15000, allocated: 12000, spent: 5600, remaining: 9400, category: 'Certifications', approvedBy: 'CTO', status: 'Active' },
      { department: 'Engineering', fiscalYear: 'FY2026', totalBudget: 10000, allocated: 7000, spent: 3200, remaining: 6800, category: 'Conferences', approvedBy: 'CTO', status: 'Active' },
      { department: 'Data Science', fiscalYear: 'FY2026', totalBudget: 8000, allocated: 6000, spent: 4500, remaining: 3500, category: 'Certifications', approvedBy: 'VP Engineering', status: 'Active' },
      { department: 'Engineering', fiscalYear: 'FY2025', totalBudget: 43000, allocated: 43000, spent: 41200, remaining: 1800, category: 'All Training', approvedBy: 'CTO', status: 'Closed' },
      { department: 'All Departments', fiscalYear: 'FY2026', totalBudget: 5000, allocated: 3000, spent: 0, remaining: 5000, category: 'Wellness', approvedBy: 'CHRO', status: 'Active' },
      { department: 'All Departments', fiscalYear: 'FY2026', totalBudget: 20000, allocated: 8000, spent: 2500, remaining: 17500, category: 'Leadership Development', approvedBy: 'CEO', status: 'Active' },
    ]);
    console.log('Learning Budgets seeded.');

    await CompetencyFramework.bulkCreate([
      { name: 'Frontend Engineering Competency', category: 'Technical', department: 'Engineering', level: 'All Levels', description: 'Frontend development skills framework', proficiencyLevels: [{level:1,label:'Novice'},{level:2,label:'Beginner'},{level:3,label:'Intermediate'},{level:4,label:'Advanced'},{level:5,label:'Expert'}], requiredSkills: ['HTML/CSS','JavaScript','React','TypeScript','Testing'], assessmentCriteria: 'Code review quality, project delivery, technical interviews', status: 'Active', version: '2.0' },
      { name: 'Backend Engineering Competency', category: 'Technical', department: 'Engineering', level: 'All Levels', description: 'Backend development skills framework', proficiencyLevels: [{level:1,label:'Novice'},{level:2,label:'Beginner'},{level:3,label:'Intermediate'},{level:4,label:'Advanced'},{level:5,label:'Expert'}], requiredSkills: ['Java/Python','Databases','APIs','Microservices','System Design'], status: 'Active', version: '2.0' },
      { name: 'Data Science Competency', category: 'Technical', department: 'Data Science', level: 'All Levels', description: 'Data science and ML skills', proficiencyLevels: [{level:1,label:'Novice'},{level:2,label:'Beginner'},{level:3,label:'Intermediate'},{level:4,label:'Advanced'},{level:5,label:'Expert'}], requiredSkills: ['Python','Statistics','ML','Deep Learning','MLOps'], status: 'Active', version: '1.5' },
      { name: 'Product Management Competency', category: 'Behavioral', department: 'Product', level: 'Mid-Senior', description: 'PM skills framework', requiredSkills: ['Strategy','User Research','Analytics','Roadmapping','Stakeholder Management'], status: 'Active', version: '1.0' },
      { name: 'UX Design Competency', category: 'Technical', department: 'Design', level: 'All Levels', description: 'UX design skills framework', requiredSkills: ['User Research','Wireframing','Prototyping','Usability Testing','Design Systems'], status: 'Active', version: '1.0' },
      { name: 'Leadership Competency', category: 'Leadership', department: 'All', level: 'Senior+', description: 'Leadership skills for managers and above', requiredSkills: ['Communication','Decision Making','Team Building','Strategic Thinking','Coaching'], status: 'Active', version: '3.0' },
      { name: 'DevOps Engineering Competency', category: 'Technical', department: 'Engineering', level: 'All Levels', description: 'DevOps and SRE skills', requiredSkills: ['CI/CD','Docker','Kubernetes','Cloud','Monitoring'], status: 'Active', version: '1.5' },
      { name: 'Cybersecurity Competency', category: 'Technical', department: 'Security', level: 'All Levels', description: 'Security engineering skills', requiredSkills: ['Network Security','AppSec','Cloud Security','Incident Response','Compliance'], status: 'Active', version: '2.0' },
      { name: 'Sales Excellence Competency', category: 'Behavioral', department: 'Sales', level: 'All Levels', description: 'Sales performance framework', requiredSkills: ['Prospecting','Negotiation','CRM','Presentation','Closing'], status: 'Active', version: '1.0' },
      { name: 'Marketing Analytics Competency', category: 'Technical', department: 'Marketing', level: 'Mid-Senior', description: 'Marketing analytics skills', requiredSkills: ['Google Analytics','SEO','Content Strategy','Marketing Automation','Data Analysis'], status: 'Draft', version: '0.5' },
      { name: 'Financial Analysis Competency', category: 'Technical', department: 'Finance', level: 'All Levels', description: 'Financial analysis skills', requiredSkills: ['Financial Modeling','Forecasting','Budgeting','Reporting','Risk Analysis'], status: 'Active', version: '1.0' },
      { name: 'HR Business Partner Competency', category: 'Behavioral', department: 'HR', level: 'Mid-Senior', description: 'HRBP skills framework', requiredSkills: ['Talent Management','Employment Law','Analytics','Change Management','Coaching'], status: 'Active', version: '1.0' },
      { name: 'Cloud Architecture Competency', category: 'Technical', department: 'Engineering', level: 'Senior+', description: 'Cloud architecture and design', requiredSkills: ['AWS','Azure','GCP','System Design','Cost Optimization'], status: 'Active', version: '1.0' },
      { name: 'Mobile Development Competency', category: 'Technical', department: 'Engineering', level: 'All Levels', description: 'Mobile app development skills', requiredSkills: ['React Native','Swift','Kotlin','Flutter','Mobile Testing'], status: 'Draft', version: '0.8' },
      { name: 'Communication & Influence', category: 'Behavioral', department: 'All', level: 'All Levels', description: 'Cross-functional communication skills', requiredSkills: ['Presentation','Writing','Active Listening','Stakeholder Management','Conflict Resolution'], status: 'Active', version: '2.0' },
    ]);
    console.log('Competency Frameworks seeded.');

    await OnboardingPlan.bulkCreate([
      { employeeId: 3, planName: 'Data Analyst 90-Day Onboarding', department: 'Data Science', startDate: '2023-01-10', targetCompletionDate: '2023-04-10', status: 'Completed', progressPercent: 100, milestones: [{name:'Week 1: Tool Setup',completed:true},{name:'Week 2: Team Introductions',completed:true},{name:'Month 1: First Report',completed:true},{name:'Month 2: Independent Projects',completed:true},{name:'Month 3: Peer Review',completed:true}], assignedBuddy: 'Leo Garcia' },
      { employeeId: 8, planName: 'Frontend Engineer 90-Day Plan', department: 'Engineering', startDate: '2023-06-15', targetCompletionDate: '2023-09-15', status: 'Completed', progressPercent: 100, milestones: [{name:'Dev Environment Setup',completed:true},{name:'Codebase Walkthrough',completed:true},{name:'First PR Merged',completed:true},{name:'Solo Feature Delivery',completed:true}], assignedBuddy: 'Alice Johnson' },
      { employeeId: 5, planName: 'UX Designer Onboarding', department: 'Design', startDate: '2022-02-14', targetCompletionDate: '2022-05-14', status: 'Completed', progressPercent: 100, milestones: [{name:'Design Tool Setup',completed:true},{name:'Brand Guidelines Review',completed:true},{name:'First Design Deliverable',completed:true}], assignedBuddy: 'Eva Martinez (self-guided)' },
      { employeeId: 14, planName: 'Security Engineer Onboarding', department: 'Security', startDate: '2022-05-01', targetCompletionDate: '2022-08-01', status: 'Completed', progressPercent: 100, milestones: [{name:'Security Tool Access',completed:true},{name:'Vulnerability Assessment Training',completed:true},{name:'First Pentest Report',completed:true}], assignedBuddy: 'CISO Direct Report' },
      { employeeId: 15, planName: 'Mobile Developer Onboarding', department: 'Engineering', startDate: '2021-11-10', targetCompletionDate: '2022-02-10', status: 'Completed', progressPercent: 100, milestones: [{name:'Mobile Dev Setup',completed:true},{name:'App Architecture Review',completed:true},{name:'First Feature Ship',completed:true}], assignedBuddy: 'Frank Lee' },
      { employeeId: 7, planName: 'Marketing Analyst Onboarding', department: 'Marketing', startDate: '2021-09-01', targetCompletionDate: '2021-12-01', status: 'Completed', progressPercent: 100, milestones: [{name:'Analytics Access',completed:true},{name:'Campaign Review',completed:true},{name:'First Analysis Report',completed:true}], assignedBuddy: 'Marketing Director' },
      { employeeId: 11, planName: 'QA Engineer Onboarding', department: 'Engineering', startDate: '2021-03-22', targetCompletionDate: '2021-06-22', status: 'Completed', progressPercent: 100, milestones: [{name:'Test Environment Setup',completed:true},{name:'Test Framework Training',completed:true},{name:'Independent Test Cycle',completed:true}], assignedBuddy: 'QA Lead' },
      { employeeId: 2, planName: 'DevOps Engineer Onboarding', department: 'Engineering', startDate: '2021-07-01', targetCompletionDate: '2021-10-01', status: 'Completed', progressPercent: 100, milestones: [{name:'Infrastructure Access',completed:true},{name:'CI/CD Pipeline Review',completed:true},{name:'First Deploy',completed:true}], assignedBuddy: 'Peter Kim' },
      { employeeId: 1, planName: 'New Employee General Onboarding', department: 'Engineering', startDate: '2026-03-01', targetCompletionDate: '2026-06-01', status: 'In Progress', progressPercent: 45, milestones: [{name:'HR Orientation',completed:true},{name:'Team Introduction',completed:true},{name:'Project Assignment',completed:false},{name:'90-Day Review',completed:false}], assignedBuddy: 'HR Team', notes: 'Template plan for reference' },
      { employeeId: 9, planName: 'HR Specialist Onboarding', department: 'HR', startDate: '2020-08-20', targetCompletionDate: '2020-11-20', status: 'Completed', progressPercent: 100, milestones: [{name:'HRIS System Training',completed:true},{name:'Policy Review',completed:true},{name:'First Recruitment Cycle',completed:true}], assignedBuddy: 'HR Director' },
      { employeeId: 10, planName: 'Financial Analyst Onboarding', department: 'Finance', startDate: '2019-04-10', targetCompletionDate: '2019-07-10', status: 'Completed', progressPercent: 100, milestones: [{name:'SAP Access & Training',completed:true},{name:'Financial Report Review',completed:true},{name:'First Quarterly Report',completed:true}], assignedBuddy: 'Finance Director' },
      { employeeId: 4, planName: 'Product Manager Onboarding', department: 'Product', startDate: '2019-06-20', targetCompletionDate: '2019-09-20', status: 'Completed', progressPercent: 100, milestones: [{name:'Product Suite Overview',completed:true},{name:'Customer Interviews',completed:true},{name:'First PRD',completed:true}], assignedBuddy: 'VP Product' },
      { employeeId: 6, planName: 'Backend Engineer Onboarding', department: 'Engineering', startDate: '2018-11-05', targetCompletionDate: '2019-02-05', status: 'Completed', progressPercent: 100, milestones: [{name:'Codebase Setup',completed:true},{name:'Architecture Review',completed:true},{name:'First Service Deployed',completed:true}], assignedBuddy: 'Tech Lead' },
      { employeeId: 12, planName: 'ML Engineer Onboarding', department: 'Data Science', startDate: '2020-01-08', targetCompletionDate: '2020-04-08', status: 'Completed', progressPercent: 100, milestones: [{name:'ML Infrastructure Setup',completed:true},{name:'Model Training Pipeline',completed:true},{name:'First Model in Production',completed:true}], assignedBuddy: 'Data Science Lead' },
      { employeeId: 13, planName: 'Sales Manager Onboarding', department: 'Sales', startDate: '2018-09-15', targetCompletionDate: '2018-12-15', status: 'Completed', progressPercent: 100, milestones: [{name:'CRM Training',completed:true},{name:'Territory Assignment',completed:true},{name:'First Quarter Quota',completed:true}], assignedBuddy: 'VP Sales' },
    ]);
    console.log('Onboarding Plans seeded.');

    await TeamGoal.bulkCreate([
      { title: 'Achieve 100% Cloud Migration', department: 'Engineering', category: 'Technical', description: 'Migrate all on-prem services to AWS', targetDate: '2026-12-31', status: 'On Track', progressPercent: 65, priority: 'High', keyResults: [{result:'Migrate 20 services',target:20,current:13},{result:'Zero downtime migrations',target:20,current:13}], owner: 'Peter Kim', quarter: 'FY2026' },
      { title: 'Reduce Mean Time to Recovery', department: 'Engineering', category: 'Operational', description: 'Reduce MTTR from 4 hours to under 1 hour', targetDate: '2026-06-30', status: 'At Risk', progressPercent: 40, priority: 'High', keyResults: [{result:'MTTR under 1 hour',target:1,current:2.5}], owner: 'Bob Smith', quarter: 'Q2 2026' },
      { title: 'Launch ML-Powered Recommendations', department: 'Data Science', category: 'Innovation', description: 'Build and deploy ML recommendation engine', targetDate: '2026-09-30', status: 'On Track', progressPercent: 55, priority: 'High', keyResults: [{result:'Model accuracy > 85%',target:85,current:78},{result:'A/B test lift > 10%',target:10,current:0}], owner: 'Leo Garcia', quarter: 'Q3 2026' },
      { title: 'Improve NPS Score to 70+', department: 'Product', category: 'Customer', description: 'Improve Net Promoter Score through better UX', targetDate: '2026-06-30', status: 'On Track', progressPercent: 70, priority: 'High', keyResults: [{result:'NPS Score 70+',target:70,current:62}], owner: 'David Brown', quarter: 'Q2 2026' },
      { title: 'Design System V2 Launch', department: 'Design', category: 'Technical', description: 'Launch comprehensive design system v2', targetDate: '2026-08-31', status: 'On Track', progressPercent: 35, priority: 'Medium', keyResults: [{result:'50 components built',target:50,current:18}], owner: 'Eva Martinez', quarter: 'Q3 2026' },
      { title: 'Increase Organic Traffic 50%', department: 'Marketing', category: 'Growth', description: 'Double organic search traffic YoY', targetDate: '2026-12-31', status: 'On Track', progressPercent: 30, priority: 'High', keyResults: [{result:'+50% organic traffic',target:50,current:15}], owner: 'Grace Chen', quarter: 'FY2026' },
      { title: 'Exceed Q2 Revenue Target', department: 'Sales', category: 'Revenue', description: 'Achieve $2.5M in Q2 sales', targetDate: '2026-06-30', status: 'On Track', progressPercent: 45, priority: 'High', keyResults: [{result:'$2.5M revenue',target:2500000,current:1125000}], owner: 'Maria Rodriguez', quarter: 'Q2 2026' },
      { title: 'Zero Critical Security Incidents', department: 'Security', category: 'Operational', description: 'Maintain zero critical security breaches', targetDate: '2026-12-31', status: 'On Track', progressPercent: 25, priority: 'High', keyResults: [{result:'0 critical incidents',target:0,current:0},{result:'100% patch compliance',target:100,current:92}], owner: 'Nathan Park', quarter: 'FY2026' },
      { title: 'Reduce Employee Turnover to 8%', department: 'HR', category: 'People', description: 'Lower voluntary turnover rate', targetDate: '2026-12-31', status: 'At Risk', progressPercent: 20, priority: 'Medium', keyResults: [{result:'Turnover rate < 8%',target:8,current:11}], owner: 'Iris Taylor', quarter: 'FY2026' },
      { title: 'Implement Real-Time Financial Dashboard', department: 'Finance', category: 'Technical', description: 'Build live financial reporting dashboard', targetDate: '2026-06-30', status: 'Behind', progressPercent: 15, priority: 'Medium', keyResults: [{result:'Dashboard live with 10 KPIs',target:10,current:2}], owner: 'Jack Anderson', quarter: 'Q2 2026' },
      { title: 'Achieve SOC 2 Type II Compliance', department: 'Security', category: 'Compliance', description: 'Complete SOC 2 Type II audit', targetDate: '2026-09-30', status: 'On Track', progressPercent: 50, priority: 'High', keyResults: [{result:'All controls implemented',target:100,current:50}], owner: 'Nathan Park', quarter: 'Q3 2026' },
      { title: '95% Test Coverage for Core Services', department: 'Engineering', category: 'Quality', description: 'Achieve comprehensive test coverage', targetDate: '2026-06-30', status: 'On Track', progressPercent: 60, priority: 'Medium', keyResults: [{result:'Test coverage > 95%',target:95,current:82}], owner: 'Karen Davis', quarter: 'Q2 2026' },
      { title: 'Launch Mobile App V2', department: 'Engineering', category: 'Product', description: 'Release redesigned mobile app', targetDate: '2026-07-31', status: 'On Track', progressPercent: 40, priority: 'High', keyResults: [{result:'All features shipped',target:15,current:6}], owner: 'Olivia White', quarter: 'Q3 2026' },
      { title: 'L&D Program Satisfaction > 90%', department: 'HR', category: 'People', description: 'Achieve high L&D program satisfaction', targetDate: '2026-12-31', status: 'On Track', progressPercent: 75, priority: 'Medium', keyResults: [{result:'Satisfaction > 90%',target:90,current:87}], owner: 'Iris Taylor', quarter: 'FY2026' },
      { title: 'Reduce Infrastructure Costs 20%', department: 'Engineering', category: 'Cost', description: 'Optimize cloud spending', targetDate: '2026-06-30', status: 'On Track', progressPercent: 55, priority: 'High', keyResults: [{result:'-20% cloud cost',target:20,current:11}], owner: 'Peter Kim', quarter: 'Q2 2026' },
    ]);
    console.log('Team Goals seeded.');

    await KnowledgeBase.bulkCreate([
      { title: 'React Best Practices Guide', author: 'Alice Johnson', category: 'Technical Guide', department: 'Engineering', content: 'Comprehensive guide to React patterns, hooks, and performance optimization techniques used in our codebase.', tags: ['React','JavaScript','Frontend','Best Practices'], status: 'Published', views: 342, rating: 4.8, lastUpdated: '2026-02-15' },
      { title: 'Kubernetes Deployment Playbook', author: 'Bob Smith', category: 'How-To', department: 'Engineering', content: 'Step-by-step guide for deploying services to our Kubernetes clusters, including rollback procedures.', tags: ['Kubernetes','DevOps','Deployment'], status: 'Published', views: 256, rating: 4.6, lastUpdated: '2026-01-20' },
      { title: 'Data Pipeline Architecture Overview', author: 'Leo Garcia', category: 'Technical Guide', department: 'Data Science', content: 'Overview of our data pipeline architecture, including ingestion, processing, and serving layers.', tags: ['Data','Architecture','Pipeline','ETL'], status: 'Published', views: 189, rating: 4.5, lastUpdated: '2026-02-01' },
      { title: 'Product PRD Template', author: 'David Brown', category: 'Template', department: 'Product', content: 'Standard PRD template with sections for problem statement, success metrics, requirements, and timeline.', tags: ['Product','Template','PRD'], status: 'Published', views: 445, rating: 4.7, lastUpdated: '2026-01-10' },
      { title: 'Design System Component Guide', author: 'Eva Martinez', category: 'Technical Guide', department: 'Design', content: 'Documentation for all design system components with usage guidelines and accessibility notes.', tags: ['Design System','Components','Accessibility'], status: 'Published', views: 312, rating: 4.4, lastUpdated: '2026-02-20' },
      { title: 'Incident Response Handbook', author: 'Nathan Park', category: 'Best Practice', department: 'Security', content: 'Complete incident response procedures including severity classification, communication protocols, and post-mortem templates.', tags: ['Security','Incident Response','On-Call'], status: 'Published', views: 567, rating: 4.9, lastUpdated: '2026-03-01' },
      { title: 'Onboarding New Engineers', author: 'Frank Lee', category: 'How-To', department: 'Engineering', content: 'Guide for mentors: how to onboard new engineers effectively including codebase walkthrough and pair programming tips.', tags: ['Onboarding','Mentoring','Engineering'], status: 'Published', views: 234, rating: 4.3, lastUpdated: '2025-12-15' },
      { title: 'API Design Standards', author: 'Frank Lee', category: 'Best Practice', department: 'Engineering', content: 'REST API design standards including naming conventions, versioning, error handling, and pagination.', tags: ['API','REST','Standards','Backend'], status: 'Published', views: 389, rating: 4.7, lastUpdated: '2026-01-25' },
      { title: 'Marketing Attribution Model', author: 'Grace Chen', category: 'Technical Guide', department: 'Marketing', content: 'Explanation of our multi-touch attribution model and how to interpret marketing channel performance data.', tags: ['Marketing','Attribution','Analytics'], status: 'Published', views: 98, rating: 4.2, lastUpdated: '2026-02-10' },
      { title: 'Performance Review Best Practices', author: 'Iris Taylor', category: 'Best Practice', department: 'HR', content: 'Guide for managers on conducting effective performance reviews with feedback frameworks and bias mitigation.', tags: ['HR','Performance','Management'], status: 'Published', views: 478, rating: 4.6, lastUpdated: '2026-01-05' },
      { title: 'Financial Forecasting Methods', author: 'Jack Anderson', category: 'Technical Guide', department: 'Finance', content: 'Overview of forecasting methodologies used in our financial planning process including Monte Carlo simulations.', tags: ['Finance','Forecasting','Modeling'], status: 'Published', views: 134, rating: 4.4, lastUpdated: '2025-11-20' },
      { title: 'Testing Strategy Guide', author: 'Karen Davis', category: 'Best Practice', department: 'Engineering', content: 'Our testing pyramid strategy: unit tests, integration tests, e2e tests, and when to use each.', tags: ['Testing','QA','Automation','Best Practices'], status: 'Published', views: 267, rating: 4.5, lastUpdated: '2026-02-05' },
      { title: 'ML Model Deployment Guide', author: 'Leo Garcia', category: 'How-To', department: 'Data Science', content: 'Step-by-step guide for deploying ML models to production including monitoring and A/B testing setup.', tags: ['ML','Deployment','MLOps','Production'], status: 'Published', views: 178, rating: 4.8, lastUpdated: '2026-03-10' },
      { title: 'Sales Playbook 2026', author: 'Maria Rodriguez', category: 'Best Practice', department: 'Sales', content: 'Updated sales playbook with objection handling scripts, demo flows, and competitive positioning.', tags: ['Sales','Playbook','Strategy'], status: 'Under Review', views: 89, rating: 4.3, lastUpdated: '2026-03-15' },
      { title: 'Cloud Cost Optimization Guide', author: 'Peter Kim', category: 'How-To', department: 'Engineering', content: 'Practical guide to reducing AWS costs: reserved instances, spot instances, right-sizing, and cleanup strategies.', tags: ['AWS','Cost','Cloud','Optimization'], status: 'Published', views: 298, rating: 4.7, lastUpdated: '2026-02-28' },
    ]);
    console.log('Knowledge Base seeded.');

    await FeedbackSurvey.bulkCreate([
      { employeeId: 1, surveyTitle: 'React Advanced Training Feedback', type: 'Post-Training', relatedItem: 'Complete React Developer', overallRating: 4.5, contentRating: 4.8, instructorRating: 4.2, applicabilityRating: 4.5, comments: 'Excellent course, very applicable to our codebase', status: 'Completed', submittedDate: '2025-12-10' },
      { employeeId: 2, surveyTitle: 'K8s Workshop Feedback', type: 'Post-Training', relatedItem: 'Kubernetes for Developers', overallRating: 4.0, contentRating: 4.2, instructorRating: 4.0, applicabilityRating: 3.8, comments: 'Good content but needed more hands-on labs', status: 'Completed', submittedDate: '2025-11-20' },
      { employeeId: 3, surveyTitle: 'Q4 2025 Learning Experience', type: 'Quarterly', overallRating: 4.2, contentRating: 4.0, instructorRating: 4.5, applicabilityRating: 4.0, comments: 'Great support from mentor Leo', status: 'Completed', submittedDate: '2026-01-05' },
      { employeeId: 4, surveyTitle: 'Product Management Course Review', type: 'Course', relatedItem: 'Product Management Fundamentals', overallRating: 3.8, contentRating: 4.0, instructorRating: 3.5, applicabilityRating: 4.0, comments: 'Good foundations but wanted more advanced content', status: 'Completed', submittedDate: '2025-10-15' },
      { employeeId: 5, surveyTitle: 'Design Thinking Workshop Feedback', type: 'Event', relatedItem: 'Design Thinking Workshop', overallRating: 4.8, contentRating: 4.5, instructorRating: 5.0, applicabilityRating: 4.8, comments: 'Best workshop this year!', status: 'Completed', submittedDate: '2026-01-25' },
      { employeeId: 6, surveyTitle: 'Spring Cloud Course Review', type: 'Post-Training', relatedItem: 'Spring Boot Microservices', overallRating: 4.5, contentRating: 4.5, instructorRating: 4.5, applicabilityRating: 4.5, comments: 'Directly applicable to our architecture', status: 'Completed', submittedDate: '2025-09-10' },
      { employeeId: 7, surveyTitle: 'Marketing Cert Feedback', type: 'Post-Training', relatedItem: 'HubSpot Marketing Certification', overallRating: 3.5, contentRating: 3.8, instructorRating: 3.2, applicabilityRating: 3.5, comments: 'Basic content, good for beginners', status: 'Completed', submittedDate: '2025-12-20' },
      { employeeId: 8, surveyTitle: 'Q1 2026 Learning Survey', type: 'Quarterly', overallRating: 4.0, contentRating: 4.0, instructorRating: 4.2, applicabilityRating: 3.8, comments: 'TypeScript course is challenging but valuable', status: 'Completed', submittedDate: '2026-03-15' },
      { employeeId: 9, surveyTitle: 'HR Analytics Course Review', type: 'Course', relatedItem: 'People Analytics Intro', overallRating: 3.8, contentRating: 3.5, instructorRating: 4.0, applicabilityRating: 4.0, comments: 'Need more HR-specific examples', status: 'Completed', submittedDate: '2025-11-30' },
      { employeeId: 10, surveyTitle: 'Financial Modeling Feedback', type: 'Post-Training', relatedItem: 'Financial Modeling & Valuation', overallRating: 4.8, contentRating: 5.0, instructorRating: 4.5, applicabilityRating: 4.8, comments: 'Exceptional quality, worth every penny', status: 'Completed', submittedDate: '2025-08-20' },
      { employeeId: 11, surveyTitle: '2025 Annual L&D Survey', type: 'Annual', overallRating: 4.0, contentRating: 4.0, instructorRating: 4.0, applicabilityRating: 4.0, comments: 'Good training budget, wish more automation courses available', status: 'Completed', submittedDate: '2026-01-15' },
      { employeeId: 12, surveyTitle: 'ML Conference Feedback', type: 'Event', relatedItem: 'Data Science Summit', overallRating: 4.5, contentRating: 4.8, instructorRating: 4.2, applicabilityRating: 4.5, comments: 'Great networking and cutting-edge content', status: 'Completed', submittedDate: '2025-07-15' },
      { employeeId: 13, surveyTitle: 'Sales Training Review', type: 'Post-Training', relatedItem: 'Strategic Sales Leadership', overallRating: 4.2, contentRating: 4.0, instructorRating: 4.5, applicabilityRating: 4.0, comments: 'Practical frameworks for team management', status: 'Completed', submittedDate: '2025-12-05' },
      { employeeId: 14, surveyTitle: 'Security Bootcamp Feedback', type: 'Post-Training', relatedItem: 'Cybersecurity Bootcamp', overallRating: 4.8, contentRating: 5.0, instructorRating: 4.8, applicabilityRating: 4.5, comments: 'Intensive and highly valuable', status: 'Completed', submittedDate: '2025-10-01' },
      { employeeId: 15, surveyTitle: 'Mobile Dev Course Survey', type: 'Course', relatedItem: 'React Native Practical Guide', overallRating: 3.5, contentRating: 3.8, instructorRating: 3.2, applicabilityRating: 3.5, comments: 'Outdated content, needs updating', status: 'Completed', submittedDate: '2025-12-15' },
    ]);
    console.log('Feedback Surveys seeded.');

    await SuccessionPlan.bulkCreate([
      { targetRole: 'VP Engineering', department: 'Engineering', candidateId: 16, currentIncumbent: 'Sarah Manager', readinessLevel: 'Ready in 1 Year', priority: 'Critical', developmentAreas: ['Executive Communication','Budget Management','Org Design'], developmentPlan: 'Complete leadership bootcamp and shadow VP for Q2', status: 'Active', targetDate: '2027-06-30', riskLevel: 'High' },
      { targetRole: 'Engineering Manager', department: 'Engineering', candidateId: 6, currentIncumbent: 'TBD (New Role)', readinessLevel: 'Ready Now', priority: 'High', developmentAreas: ['People Management','Hiring','Performance Reviews'], status: 'Active', targetDate: '2026-09-30', riskLevel: 'Low' },
      { targetRole: 'Staff Engineer', department: 'Engineering', candidateId: 1, currentIncumbent: 'N/A', readinessLevel: 'Ready in 1 Year', priority: 'High', developmentAreas: ['System Design','Cross-Team Leadership','Technical Strategy'], status: 'Active', targetDate: '2027-03-31', riskLevel: 'Medium' },
      { targetRole: 'Data Science Director', department: 'Data Science', candidateId: 12, currentIncumbent: 'Current Director', readinessLevel: 'Ready in 1 Year', priority: 'High', developmentAreas: ['Team Leadership','Stakeholder Management','Budget Planning'], status: 'Active', targetDate: '2027-06-30', riskLevel: 'Medium' },
      { targetRole: 'Head of Product', department: 'Product', candidateId: 4, currentIncumbent: 'VP Product', readinessLevel: 'Ready in 2+ Years', priority: 'Medium', developmentAreas: ['Executive Presence','P&L Management','Board Presentations'], status: 'Active', targetDate: '2028-12-31', riskLevel: 'Low' },
      { targetRole: 'Design Director', department: 'Design', candidateId: 5, currentIncumbent: 'Current Director', readinessLevel: 'Ready in 2+ Years', priority: 'Medium', developmentAreas: ['Design Operations','Team Scaling','Executive Reporting'], status: 'Active', targetDate: '2028-06-30', riskLevel: 'Low' },
      { targetRole: 'VP Sales', department: 'Sales', candidateId: 13, currentIncumbent: 'Current VP', readinessLevel: 'Ready in 1 Year', priority: 'High', developmentAreas: ['Strategic Planning','Enterprise Sales','P&L Ownership'], status: 'Active', targetDate: '2027-03-31', riskLevel: 'Medium' },
      { targetRole: 'CISO', department: 'Security', candidateId: 14, currentIncumbent: 'Current CISO', readinessLevel: 'Ready in 2+ Years', priority: 'Medium', developmentAreas: ['Risk Management','Compliance','Executive Communication','Board Reporting'], status: 'Active', targetDate: '2028-12-31', riskLevel: 'High' },
      { targetRole: 'HR Director', department: 'HR', candidateId: 9, currentIncumbent: 'Current Director', readinessLevel: 'Ready in 1 Year', priority: 'Medium', developmentAreas: ['Employment Law','Organizational Development','HRIS Strategy'], status: 'Active', targetDate: '2027-06-30', riskLevel: 'Medium' },
      { targetRole: 'CFO', department: 'Finance', candidateId: 10, currentIncumbent: 'Current CFO', readinessLevel: 'Ready in 2+ Years', priority: 'High', developmentAreas: ['Strategic Finance','M&A','Investor Relations','Board Management'], status: 'Active', targetDate: '2029-06-30', riskLevel: 'High' },
      { targetRole: 'QA Manager', department: 'Engineering', candidateId: 11, currentIncumbent: 'QA Lead', readinessLevel: 'Ready Now', priority: 'Medium', developmentAreas: ['Team Management','Test Strategy','Stakeholder Communication'], status: 'Active', targetDate: '2026-06-30', riskLevel: 'Low' },
      { targetRole: 'Cloud Architect Lead', department: 'Engineering', candidateId: 2, currentIncumbent: 'Peter Kim', readinessLevel: 'Ready in 1 Year', priority: 'Medium', developmentAreas: ['Multi-Cloud Strategy','Cost Optimization','Architecture Reviews'], status: 'Active', targetDate: '2027-06-30', riskLevel: 'Medium' },
      { targetRole: 'Senior Data Scientist', department: 'Data Science', candidateId: 3, currentIncumbent: 'N/A', readinessLevel: 'Development Needed', priority: 'Medium', developmentAreas: ['ML Engineering','Statistical Analysis','Research Methods'], status: 'Active', targetDate: '2028-03-31', riskLevel: 'Low' },
      { targetRole: 'Marketing Director', department: 'Marketing', candidateId: 7, currentIncumbent: 'Current Director', readinessLevel: 'Ready in 2+ Years', priority: 'Low', developmentAreas: ['Brand Strategy','Team Leadership','Budget Management'], status: 'Active', targetDate: '2028-12-31', riskLevel: 'Low' },
      { targetRole: 'Mobile Lead', department: 'Engineering', candidateId: 15, currentIncumbent: 'Current Lead', readinessLevel: 'Ready in 1 Year', priority: 'Medium', developmentAreas: ['Architecture Decision Records','Team Mentoring','Cross-Platform Strategy'], status: 'Active', targetDate: '2027-03-31', riskLevel: 'Medium' },
    ]);
    console.log('Succession Plans seeded.');

    await ComplianceTraining.bulkCreate([
      { employeeId: 1, trainingName: 'Data Privacy & GDPR', regulatoryBody: 'EU', category: 'Data Privacy', dueDate: '2026-06-30', completionDate: '2026-02-15', status: 'Completed', validUntil: '2027-06-30', passingScore: 80, actualScore: 92, mandatory: true },
      { employeeId: 2, trainingName: 'Data Privacy & GDPR', regulatoryBody: 'EU', category: 'Data Privacy', dueDate: '2026-06-30', completionDate: '2026-01-20', status: 'Completed', validUntil: '2027-06-30', passingScore: 80, actualScore: 88, mandatory: true },
      { employeeId: 3, trainingName: 'Data Privacy & GDPR', regulatoryBody: 'EU', category: 'Data Privacy', dueDate: '2026-06-30', status: 'Not Started', validUntil: '2027-06-30', passingScore: 80, mandatory: true },
      { employeeId: 4, trainingName: 'Anti-Harassment Training', regulatoryBody: 'EEOC', category: 'Ethics', dueDate: '2026-03-31', completionDate: '2026-02-28', status: 'Completed', validUntil: '2027-03-31', passingScore: 80, actualScore: 95, mandatory: true },
      { employeeId: 5, trainingName: 'Workplace Safety', regulatoryBody: 'OSHA', category: 'Safety', dueDate: '2026-04-30', status: 'In Progress', validUntil: '2027-04-30', passingScore: 70, mandatory: true },
      { employeeId: 6, trainingName: 'SOX Compliance Training', regulatoryBody: 'SEC', category: 'Financial', dueDate: '2026-03-31', completionDate: '2026-03-01', status: 'Completed', validUntil: '2027-03-31', passingScore: 85, actualScore: 90, mandatory: true },
      { employeeId: 7, trainingName: 'CAN-SPAM Act Training', regulatoryBody: 'FTC', category: 'Marketing', dueDate: '2026-06-30', completionDate: '2026-01-15', status: 'Completed', validUntil: '2027-06-30', passingScore: 80, actualScore: 85, mandatory: true },
      { employeeId: 8, trainingName: 'Data Privacy & GDPR', regulatoryBody: 'EU', category: 'Data Privacy', dueDate: '2026-06-30', status: 'In Progress', validUntil: '2027-06-30', passingScore: 80, mandatory: true },
      { employeeId: 9, trainingName: 'Employment Law Updates 2026', regulatoryBody: 'DOL', category: 'Legal', dueDate: '2026-03-31', completionDate: '2026-02-10', status: 'Completed', validUntil: '2027-03-31', passingScore: 85, actualScore: 94, mandatory: true },
      { employeeId: 10, trainingName: 'SOX Compliance Training', regulatoryBody: 'SEC', category: 'Financial', dueDate: '2026-03-31', completionDate: '2026-03-05', status: 'Completed', validUntil: '2027-03-31', passingScore: 85, actualScore: 96, mandatory: true },
      { employeeId: 11, trainingName: 'Anti-Harassment Training', regulatoryBody: 'EEOC', category: 'Ethics', dueDate: '2026-03-31', status: 'Overdue', validUntil: '2027-03-31', passingScore: 80, mandatory: true },
      { employeeId: 12, trainingName: 'AI Ethics & Responsible AI', regulatoryBody: 'Internal', category: 'AI Ethics', dueDate: '2026-06-30', completionDate: '2026-02-20', status: 'Completed', validUntil: '2027-06-30', passingScore: 80, actualScore: 98, mandatory: true },
      { employeeId: 13, trainingName: 'Anti-Bribery & Corruption', regulatoryBody: 'DOJ', category: 'Ethics', dueDate: '2026-06-30', status: 'Not Started', validUntil: '2027-06-30', passingScore: 80, mandatory: true },
      { employeeId: 14, trainingName: 'HIPAA Security Awareness', regulatoryBody: 'HHS', category: 'Data Privacy', dueDate: '2026-04-30', completionDate: '2026-01-30', status: 'Completed', validUntil: '2027-04-30', passingScore: 85, actualScore: 93, mandatory: true },
      { employeeId: 15, trainingName: 'Workplace Safety', regulatoryBody: 'OSHA', category: 'Safety', dueDate: '2026-04-30', completionDate: '2026-03-10', status: 'Completed', validUntil: '2027-04-30', passingScore: 70, actualScore: 82, mandatory: true },
      { employeeId: 16, trainingName: 'Data Privacy & GDPR', regulatoryBody: 'EU', category: 'Data Privacy', dueDate: '2026-06-30', completionDate: '2026-01-05', status: 'Completed', validUntil: '2027-06-30', passingScore: 80, actualScore: 91, mandatory: true },
    ]);
    console.log('Compliance Trainings seeded.');

    await CareerPath.bulkCreate([
      { employeeId: 1, currentRole: 'Senior Software Engineer', targetRole: 'Staff Engineer', department: 'Engineering', estimatedTimeline: '12-18 months', status: 'Active', progressPercent: 40, requiredSkills: ['System Design','Technical Leadership','Architecture'], completedMilestones: ['Lead 2 major projects','Mentor 3 juniors'], nextMilestone: 'Design a distributed system', mentorName: 'Peter Kim' },
      { employeeId: 2, currentRole: 'DevOps Engineer', targetRole: 'Cloud Architect', department: 'Engineering', estimatedTimeline: '18-24 months', status: 'Active', progressPercent: 30, requiredSkills: ['Multi-Cloud','System Design','Cost Optimization'], completedMilestones: ['CKA Certification'], nextMilestone: 'AWS SA Professional cert', mentorName: 'Peter Kim' },
      { employeeId: 3, currentRole: 'Data Analyst', targetRole: 'Data Scientist', department: 'Data Science', estimatedTimeline: '18-24 months', status: 'Active', progressPercent: 25, requiredSkills: ['Machine Learning','Statistics','Python Advanced','Deep Learning'], completedMilestones: ['Google Data Analytics cert'], nextMilestone: 'Complete ML specialization', mentorName: 'Leo Garcia' },
      { employeeId: 4, currentRole: 'Product Manager', targetRole: 'Director of Product', department: 'Product', estimatedTimeline: '24-36 months', status: 'Active', progressPercent: 35, requiredSkills: ['Product Strategy','P&L','Team Leadership','Executive Presence'], completedMilestones: ['CSPO cert','Led product launch'], nextMilestone: 'Manage product team of 5+', mentorName: 'VP Product' },
      { employeeId: 5, currentRole: 'UX Designer', targetRole: 'Senior UX Designer', department: 'Design', estimatedTimeline: '12 months', status: 'Active', progressPercent: 50, requiredSkills: ['Design Systems','Research Leadership','Design Ops'], completedMilestones: ['Google UX cert','Led redesign project'], nextMilestone: 'Build design system v2', mentorName: 'Design Director' },
      { employeeId: 6, currentRole: 'Backend Engineer', targetRole: 'Engineering Manager', department: 'Engineering', estimatedTimeline: '6-12 months', status: 'Active', progressPercent: 70, requiredSkills: ['People Management','Hiring','Performance Management'], completedMilestones: ['Mentored 5 engineers','Led architecture review','Completed leadership training'], nextMilestone: 'Conduct performance reviews', mentorName: 'Sarah Manager' },
      { employeeId: 7, currentRole: 'Marketing Analyst', targetRole: 'Marketing Manager', department: 'Marketing', estimatedTimeline: '18-24 months', status: 'Active', progressPercent: 20, requiredSkills: ['Marketing Strategy','Team Leadership','Budget Management'], completedMilestones: ['SEO certification'], nextMilestone: 'Lead a campaign end-to-end', mentorName: 'Marketing Director' },
      { employeeId: 8, currentRole: 'Frontend Engineer', targetRole: 'Mid Frontend Engineer', department: 'Engineering', estimatedTimeline: '12 months', status: 'Active', progressPercent: 40, requiredSkills: ['TypeScript','Testing','Architecture Patterns'], completedMilestones: ['React basics mastery','First solo feature'], nextMilestone: 'TypeScript proficiency', mentorName: 'Alice Johnson' },
      { employeeId: 9, currentRole: 'HR Specialist', targetRole: 'HR Manager', department: 'HR', estimatedTimeline: '12-18 months', status: 'Active', progressPercent: 45, requiredSkills: ['People Analytics','Employment Law','Organizational Development'], completedMilestones: ['HRIS mastery','Led recruitment for 3 teams'], nextMilestone: 'Complete HR analytics cert', mentorName: 'HR Director' },
      { employeeId: 10, currentRole: 'Financial Analyst', targetRole: 'Finance Manager', department: 'Finance', estimatedTimeline: '12-18 months', status: 'Active', progressPercent: 55, requiredSkills: ['Financial Strategy','Team Leadership','Forecasting'], completedMilestones: ['CFA Level II','Built forecasting model'], nextMilestone: 'CFA Level III', mentorName: 'CFO' },
      { employeeId: 11, currentRole: 'QA Engineer', targetRole: 'QA Manager', department: 'Engineering', estimatedTimeline: '12 months', status: 'Active', progressPercent: 50, requiredSkills: ['Test Strategy','Team Leadership','Automation Architecture'], completedMilestones: ['ISTQB cert','Built automation framework'], nextMilestone: 'Lead QA team of 4+', mentorName: 'QA Lead' },
      { employeeId: 12, currentRole: 'ML Engineer', targetRole: 'Principal ML Engineer', department: 'Data Science', estimatedTimeline: '12-18 months', status: 'Active', progressPercent: 60, requiredSkills: ['Research','MLOps','Team Leadership','Publication'], completedMilestones: ['TensorFlow cert','3 models in production','Conference talk'], nextMilestone: 'Publish research paper', mentorName: 'Data Science Director' },
      { employeeId: 13, currentRole: 'Sales Manager', targetRole: 'VP Sales', department: 'Sales', estimatedTimeline: '24-36 months', status: 'Active', progressPercent: 35, requiredSkills: ['Strategic Planning','Enterprise Sales','P&L','Board Reporting'], completedMilestones: ['Salesforce admin cert','Exceeded quota 8 quarters'], nextMilestone: 'Manage regional team', mentorName: 'VP Sales' },
      { employeeId: 14, currentRole: 'Security Engineer', targetRole: 'Security Architect', department: 'Security', estimatedTimeline: '18-24 months', status: 'Active', progressPercent: 30, requiredSkills: ['Cloud Security','Architecture','Risk Management','Compliance'], completedMilestones: ['CompTIA Security+'], nextMilestone: 'CCSP certification', mentorName: 'CISO' },
      { employeeId: 15, currentRole: 'Mobile Developer', targetRole: 'Mobile Lead', department: 'Engineering', estimatedTimeline: '12-18 months', status: 'Active', progressPercent: 35, requiredSkills: ['Architecture','Cross-Platform Strategy','Team Leadership'], completedMilestones: ['Shipped 3 apps','Led mobile hackathon'], nextMilestone: 'Architect mobile v2', mentorName: 'Mobile Lead' },
    ]);
    console.log('Career Paths seeded.');

    await LearningResource.bulkCreate([
      { title: 'Designing Data-Intensive Applications', type: 'Book', author: 'Martin Kleppmann', category: 'System Design', description: 'The definitive guide to distributed systems design', cost: 45.99, rating: 4.9, reviewCount: 34, skillTags: ['System Design','Distributed Systems','Databases'], status: 'Available', format: 'PDF/Physical' },
      { title: 'Clean Code', type: 'Book', author: 'Robert C. Martin', category: 'Software Engineering', description: 'A handbook of agile software craftsmanship', cost: 39.99, rating: 4.6, reviewCount: 28, skillTags: ['Clean Code','Best Practices','Refactoring'], status: 'Available', format: 'PDF/Physical' },
      { title: 'System Design Interview Vol 1', type: 'Book', author: 'Alex Xu', category: 'System Design', description: 'An insider guide to system design interviews', cost: 35.00, rating: 4.8, reviewCount: 22, skillTags: ['System Design','Interviews','Architecture'], status: 'Available', format: 'PDF' },
      { title: 'Fireship YouTube Channel', type: 'Video', author: 'Jeff Delaney', category: 'Programming', description: 'Fast-paced tech tutorials and explanations', cost: 0, rating: 4.7, reviewCount: 45, skillTags: ['JavaScript','React','Firebase','Web Dev'], status: 'Available', format: 'Video' },
      { title: 'The Manager Path', type: 'Book', author: 'Camille Fournier', category: 'Leadership', description: 'A guide for tech leaders navigating growth and change', cost: 29.99, rating: 4.7, reviewCount: 19, skillTags: ['Leadership','Management','Career Growth'], status: 'Available', format: 'PDF/Audio' },
      { title: 'Software Engineering Daily', type: 'Podcast', author: 'Various', category: 'Engineering', description: 'Daily podcast on software engineering topics', cost: 0, rating: 4.3, reviewCount: 15, skillTags: ['Engineering','Architecture','Industry Trends'], status: 'Available', format: 'Audio' },
      { title: 'Towards Data Science Blog', type: 'Article', author: 'Multiple Authors', category: 'Data Science', description: 'Medium publication for data science articles', cost: 0, rating: 4.4, reviewCount: 32, skillTags: ['Data Science','ML','Python','Statistics'], status: 'Available', format: 'Web' },
      { title: 'Excalidraw', type: 'Tool', author: 'Open Source', category: 'Design', description: 'Virtual whiteboard for sketching diagrams', cost: 0, rating: 4.6, reviewCount: 41, skillTags: ['Diagramming','Architecture','Collaboration'], status: 'Available', format: 'Web App' },
      { title: 'The Lean Startup', type: 'Book', author: 'Eric Ries', category: 'Product', description: 'How today\'s entrepreneurs use continuous innovation', cost: 24.99, rating: 4.5, reviewCount: 23, skillTags: ['Product','Strategy','Innovation','Startups'], status: 'Available', format: 'PDF/Audio' },
      { title: 'AWS Well-Architected Labs', type: 'Template', author: 'AWS', category: 'Cloud', description: 'Hands-on labs for AWS Well-Architected Framework', cost: 0, rating: 4.8, reviewCount: 18, skillTags: ['AWS','Cloud','Architecture','Best Practices'], status: 'Available', format: 'Web' },
      { title: 'Refactoring Guru', type: 'Article', author: 'Alexander Shvets', category: 'Programming', description: 'Design patterns and refactoring techniques explained visually', cost: 0, rating: 4.7, reviewCount: 37, skillTags: ['Design Patterns','Refactoring','OOP'], status: 'Available', format: 'Web' },
      { title: 'Khan Academy - Statistics', type: 'Video', author: 'Sal Khan', category: 'Mathematics', description: 'Free statistics and probability course', cost: 0, rating: 4.5, reviewCount: 12, skillTags: ['Statistics','Probability','Mathematics'], status: 'Available', format: 'Video' },
      { title: 'Sprint Retrospective Template', type: 'Template', author: 'Internal', category: 'Agile', description: 'Miro template for sprint retrospectives', cost: 0, rating: 4.2, reviewCount: 8, skillTags: ['Agile','Scrum','Retrospective'], status: 'Available', format: 'Miro Template' },
      { title: 'OWASP Top 10', type: 'Article', author: 'OWASP Foundation', category: 'Security', description: 'The standard awareness document for web application security', cost: 0, rating: 4.8, reviewCount: 29, skillTags: ['Security','AppSec','Web Security'], status: 'Available', format: 'Web/PDF' },
      { title: 'Thinking, Fast and Slow', type: 'Book', author: 'Daniel Kahneman', category: 'Psychology', description: 'Understanding cognitive biases for better decision making', cost: 18.99, rating: 4.4, reviewCount: 14, skillTags: ['Decision Making','Psychology','Leadership'], status: 'Available', format: 'PDF/Audio' },
    ]);
    console.log('Learning Resources seeded.');

    await AssessmentResult.bulkCreate([
      { employeeId: 1, assessmentName: 'React Proficiency Test', type: 'Skill Check', category: 'Frontend', score: 88, maxScore: 100, passingScore: 70, passed: true, assessmentDate: '2026-01-15', duration: 60, status: 'Passed' },
      { employeeId: 1, assessmentName: 'System Design Assessment', type: 'Skill Check', category: 'Architecture', score: 62, maxScore: 100, passingScore: 70, passed: false, assessmentDate: '2026-02-01', duration: 90, status: 'Failed' },
      { employeeId: 2, assessmentName: 'AWS Knowledge Check', type: 'Pre-Training', category: 'Cloud', score: 75, maxScore: 100, passingScore: 60, passed: true, assessmentDate: '2025-12-01', duration: 45, status: 'Passed' },
      { employeeId: 3, assessmentName: 'Python Skills Assessment', type: 'Skill Check', category: 'Programming', score: 72, maxScore: 100, passingScore: 70, passed: true, assessmentDate: '2026-01-20', duration: 60, status: 'Passed' },
      { employeeId: 3, assessmentName: 'ML Foundations Pre-Test', type: 'Pre-Training', category: 'AI/ML', score: 35, maxScore: 100, passingScore: 50, passed: false, assessmentDate: '2025-11-15', duration: 45, status: 'Failed' },
      { employeeId: 4, assessmentName: 'Product Management Assessment', type: 'Annual', category: 'Product', score: 85, maxScore: 100, passingScore: 70, passed: true, assessmentDate: '2026-01-10', duration: 60, status: 'Passed' },
      { employeeId: 6, assessmentName: 'Java Certification Practice Exam', type: 'Certification', category: 'Programming', score: 92, maxScore: 100, passingScore: 75, passed: true, assessmentDate: '2026-02-15', duration: 120, status: 'Passed' },
      { employeeId: 6, assessmentName: 'AWS SA Post-Training Assessment', type: 'Post-Training', category: 'Cloud', score: 78, maxScore: 100, passingScore: 72, passed: true, assessmentDate: '2026-03-01', duration: 90, status: 'Passed' },
      { employeeId: 8, assessmentName: 'JavaScript Fundamentals Test', type: 'Skill Check', category: 'Frontend', score: 68, maxScore: 100, passingScore: 60, passed: true, assessmentDate: '2025-12-15', duration: 45, status: 'Passed' },
      { employeeId: 10, assessmentName: 'Financial Analysis Assessment', type: 'Annual', category: 'Finance', score: 94, maxScore: 100, passingScore: 80, passed: true, assessmentDate: '2026-01-10', duration: 120, status: 'Passed' },
      { employeeId: 11, assessmentName: 'Test Automation Assessment', type: 'Skill Check', category: 'QA', score: 82, maxScore: 100, passingScore: 70, passed: true, assessmentDate: '2026-02-10', duration: 60, status: 'Passed' },
      { employeeId: 12, assessmentName: 'Deep Learning Post-Training', type: 'Post-Training', category: 'AI/ML', score: 96, maxScore: 100, passingScore: 80, passed: true, assessmentDate: '2026-01-25', duration: 90, status: 'Passed' },
      { employeeId: 14, assessmentName: 'Security+ Practice Exam', type: 'Certification', category: 'Security', score: 85, maxScore: 100, passingScore: 75, passed: true, assessmentDate: '2025-11-20', duration: 90, status: 'Passed' },
      { employeeId: 15, assessmentName: 'Mobile Development Assessment', type: 'Skill Check', category: 'Mobile', score: 74, maxScore: 100, passingScore: 70, passed: true, assessmentDate: '2026-02-20', duration: 60, status: 'Passed' },
      { employeeId: 16, assessmentName: 'Cloud Architecture Assessment', type: 'Annual', category: 'Cloud', score: 98, maxScore: 100, passingScore: 85, passed: true, assessmentDate: '2026-01-05', duration: 120, status: 'Passed' },
    ]);
    console.log('Assessment Results seeded.');

    await WellnessProgram.bulkCreate([
      { programName: 'Mindfulness & Meditation Program', category: 'Mental', provider: 'Headspace for Work', description: 'Daily guided meditation sessions and mindfulness training for stress reduction', startDate: '2026-01-01', endDate: '2026-12-31', participantCount: 89, capacity: 200, cost: 0, status: 'Active', satisfactionScore: 4.6, format: 'Virtual' },
      { programName: 'Ergonomic Workspace Assessment', category: 'Physical', provider: 'ErgoWorks', description: 'Individual workstation assessments and ergonomic equipment recommendations', startDate: '2026-02-01', endDate: '2026-04-30', participantCount: 120, capacity: 150, cost: 150, status: 'Active', satisfactionScore: 4.3, format: 'In-Person' },
      { programName: 'Financial Wellness Workshop', category: 'Financial', provider: 'Fidelity', description: 'Retirement planning, investment basics, and financial goal setting workshops', startDate: '2026-03-15', endDate: '2026-03-15', participantCount: 65, capacity: 100, cost: 0, status: 'Active', satisfactionScore: 4.4, format: 'Hybrid' },
      { programName: 'Team Building Adventure Day', category: 'Social', provider: 'Adventure Corp', description: 'Outdoor team activities including hiking, kayaking, and collaborative challenges', startDate: '2026-05-20', endDate: '2026-05-20', participantCount: 0, capacity: 80, cost: 75, status: 'Upcoming', satisfactionScore: 0, format: 'In-Person' },
      { programName: 'Flexible Work Coaching', category: 'Work-Life Balance', provider: 'Internal HR', description: 'One-on-one coaching sessions for optimizing hybrid work arrangements', startDate: '2026-01-15', endDate: '2026-06-30', participantCount: 34, capacity: 50, cost: 0, status: 'Active', satisfactionScore: 4.7, format: 'Virtual' },
      { programName: 'Yoga & Stretching Classes', category: 'Physical', provider: 'YogaFit Corporate', description: 'Weekly yoga sessions for desk workers focusing on posture and flexibility', startDate: '2026-01-01', endDate: '2026-12-31', participantCount: 42, capacity: 30, cost: 0, status: 'Active', satisfactionScore: 4.8, format: 'Hybrid' },
      { programName: 'Employee Assistance Program (EAP)', category: 'Mental', provider: 'LifeWorks', description: 'Confidential counseling, legal, and financial advisory services', startDate: '2026-01-01', endDate: '2026-12-31', participantCount: 28, capacity: 500, cost: 0, status: 'Active', satisfactionScore: 4.5, format: 'Virtual' },
      { programName: 'Nutrition & Healthy Eating Seminar', category: 'Physical', provider: 'Dr. Lisa Chen', description: 'Nutrition workshop covering meal planning, healthy snacking, and energy management', startDate: '2026-04-10', endDate: '2026-04-10', participantCount: 0, capacity: 60, cost: 0, status: 'Upcoming', satisfactionScore: 0, format: 'In-Person' },
      { programName: 'Stress Management Bootcamp', category: 'Mental', provider: 'Calm for Business', description: 'Intensive 4-week program on stress management techniques and resilience building', startDate: '2026-02-01', endDate: '2026-02-28', participantCount: 56, capacity: 60, cost: 0, status: 'Completed', satisfactionScore: 4.5, format: 'Virtual' },
      { programName: 'Walking Meetings Initiative', category: 'Physical', provider: 'Internal', description: 'Encourage walking meetings for 1-on-1s. Pedometer challenge included!', startDate: '2026-03-01', endDate: '2026-05-31', participantCount: 78, capacity: 200, cost: 0, status: 'Active', satisfactionScore: 4.2, format: 'In-Person' },
      { programName: 'Parenting Support Group', category: 'Work-Life Balance', provider: 'Internal HR', description: 'Monthly support group for working parents with expert guest speakers', startDate: '2026-01-15', endDate: '2026-12-31', participantCount: 22, capacity: 30, cost: 0, status: 'Active', satisfactionScore: 4.6, format: 'Hybrid' },
      { programName: 'Annual Health Screening', category: 'Physical', provider: 'HealthCorp', description: 'Comprehensive health screenings including blood work, vision, and hearing', startDate: '2026-06-01', endDate: '2026-06-15', participantCount: 0, capacity: 300, cost: 0, status: 'Upcoming', satisfactionScore: 0, format: 'In-Person' },
      { programName: 'Digital Detox Challenge', category: 'Mental', provider: 'Internal', description: '30-day challenge to reduce screen time outside work hours', startDate: '2026-04-01', endDate: '2026-04-30', participantCount: 0, capacity: 100, cost: 0, status: 'Upcoming', satisfactionScore: 0, format: 'Self-Paced' },
      { programName: 'Volunteer Day Program', category: 'Social', provider: 'Internal CSR', description: 'Quarterly volunteer days at local charities and community organizations', startDate: '2026-01-01', endDate: '2026-12-31', participantCount: 95, capacity: 150, cost: 0, status: 'Active', satisfactionScore: 4.9, format: 'In-Person' },
      { programName: 'Sleep Optimization Workshop', category: 'Physical', provider: 'Dr. Matthew Walker', description: 'Evidence-based strategies for improving sleep quality and productivity', startDate: '2026-03-25', endDate: '2026-03-25', participantCount: 45, capacity: 100, cost: 0, status: 'Completed', satisfactionScore: 4.7, format: 'Virtual' },
    ]);
    console.log('Wellness Programs seeded.');

    console.log('\n=== All data seeded successfully! ===');
    console.log('Demo accounts were created with the caller-supplied password.');
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
}

seed();
